from facts1 import F, add

# ===================== PERU / INCAS =====================
add("Peru", "Incas", [
 ("What did the Incas call their empire?", "Tawantinsuyu, 'the four parts together'", "Tenochtitlan", "Qhapaq Ñan", "Inti Raymi"),
 ("Capital of the Inca Empire?", "Cusco", "Machu Picchu", "Lima", "Quito"),
 ("Which Inca ruler began the rapid expansion around 1438?", "Pachacuti", "Atahualpa", "Manco Cápac", "Huáscar"),
 ("The Incas' main god, the sun?", "Inti", "Viracocha", "Pachamama", "Huitzilopochtli"),
 ("Pachamama is…?", "Mother Earth", "The sun god", "The god of war", "The moon"),
 ("Instead of writing, the Incas recorded data on knotted cords called…?", "Quipu", "Codex", "Tocapu", "Glyphs"),
 ("The Inca road network is called…?", "Qhapaq Ñan", "Inca Express", "Camino Real", "Tawantinsuyu"),
 ("Roughly how long was the Inca road network?", "About 30,000–40,000 km", "About 500 km", "About 3,000 km", "About 150,000 km"),
 ("Inca relay runners who carried messages were called…?", "Chasquis", "Curacas", "Amautas", "Mitimaes"),
 ("The Inca title for the emperor?", "Sapa Inca", "Tlatoani", "Kuraka", "Huaca"),
 ("Which two brothers fought an Inca civil war just before the Spanish arrived?", "Atahualpa and Huáscar", "Pachacuti and Túpac", "Manco and Paullu", "Huayna and Inti"),
 ("What killed Emperor Huayna Cápac, triggering the succession war?", "Smallpox that spread ahead of the Spanish", "A Spanish ambush", "A llama stampede", "A battle with the Aztecs"),
 ("Inca stonework is famous because…?", "Blocks fit so tightly without mortar that a blade won't slip in", "It's carved from gold", "It's all one giant rock", "It uses Roman concrete"),
 ("Inca 'Inti Raymi' is the festival of…?", "The sun, at the winter solstice", "The harvest moon", "The new emperor", "The rains"),
])
add("Peru", "Pizarro & the conquest", [
 ("Where was Francisco Pizarro from?", "Trujillo, in Extremadura, Spain", "Seville", "Lisbon", "Genoa"),
 ("On which island did Pizarro draw his famous line in the sand in 1527?", "Isla del Gallo", "Isla del Sol", "Gorgona", "Isla de Pascua"),
 ("What did Pizarro say as he drew the line, roughly?", "On this side lie riches in Peru, on that side poverty in Panama", "For God and Spain, follow me", "Gold or death", "There is no turning back"),
 ("How many men crossed the line to stay with Pizarro?", "13, 'the Famous Thirteen'", "160", "50", "3"),
 ("Who was Pizarro's partner in the early Peru expeditions, later his rival?", "Diego de Almagro", "Hernán Cortés", "Vasco Núñez de Balboa", "Pedro de Valdivia"),
 ("Which 1529 agreement with the Spanish Crown licensed Pizarro to conquer Peru?", "The Capitulación de Toledo", "The Treaty of Tordesillas", "The Laws of Burgos", "The Edict of Granada"),
 ("Was the conquest mainly paid for by the King of Spain?", "No, it was a privately funded venture", "Yes, fully", "Yes, by the Pope", "By Portugal"),
 ("Roughly how many Spaniards were with Pizarro at Cajamarca in 1532?", "About 170", "About 5,000", "About 13", "About 1,000"),
 ("Which Inca emperor did Pizarro capture at Cajamarca?", "Atahualpa", "Huáscar", "Pachacuti", "Manco Inca"),
 ("Why were horses such a shock to the Incas?", "They'd never seen horses, and cavalry was devastating", "Horses were sacred to them", "They had larger horses", "Horses were forbidden in the Andes"),
 ("What ransom did Atahualpa offer for his release?", "To fill a room with gold and two with silver", "A thousand llamas", "His own crown", "The city of Cusco"),
 ("What happened to Atahualpa after the ransom was paid?", "The Spanish executed him in 1533", "He was freed", "He escaped to the jungle", "He was sent to Spain"),
 ("How did Pizarro die in 1541?", "Assassinated in Lima by Almagro's supporters", "In battle with the Incas", "Of old age in Spain", "Executed by the king"),
 ("Which city did Pizarro found in 1535 as the new capital?", "Lima", "Cusco", "Arequipa", "Trujillo"),
 ("Besides steel and horses, what most helped the Spanish beat the Incas?", "Disease and the Inca civil war", "Superior numbers", "An alliance with the Aztecs", "Gunpowder ships"),
 ("Which Inca leader led a long resistance from Vilcabamba after the conquest?", "Manco Inca", "Atahualpa", "Huayna Cápac", "Pachacuti"),
 ("Who was the last Inca ruler, executed in 1572?", "Túpac Amaru", "Atahualpa", "Manco Inca", "Huáscar"),
])
add("Peru", "Quechua", [
 ("What language did the Incas speak?", "Quechua", "Aymara", "Nahuatl", "Guaraní"),
 ("Roughly how many people speak Quechua today?", "About 8–10 million", "About 50,000", "About 50 million", "Nobody, it's extinct"),
 ("How do you say 'thank you' in Cusco Quechua?", "Añay (also sulpayki)", "Allillanchu", "Tupananchiskama", "Imaynalla"),
 ("What does 'tupananchiskama' mean?", "Until we meet again", "Thank you", "Good morning", "Cheers"),
 ("Quechua famously lacks a simple word for…?", "Goodbye, people say 'until we meet again'", "Thank you", "Water", "Mother"),
 ("What does 'allillanchu?' mean?", "How are you?", "Thank you", "Goodbye", "Cheers"),
 ("Which everyday English words come from Quechua?", "Llama, condor, puma, jerky", "Chocolate, tomato, avocado", "Canoe, hurricane, barbecue", "Kayak, igloo, parka"),
 ("Besides Spanish and Quechua, Peru's other major Indigenous language?", "Aymara", "Guaraní", "Mapudungun", "Nahuatl"),
])
add("Peru", "Cusco & Sacred Valley", [
 ("Cusco was laid out in the shape of which animal?", "A puma", "A condor", "A llama", "A snake"),
 ("Which fortress forms the puma's head in Cusco's layout?", "Sacsayhuamán", "Ollantaytambo", "Qorikancha", "Pisac"),
 ("Cusco's Inca sun temple, later topped by a Spanish convent?", "Qorikancha", "Sacsayhuamán", "Tambomachay", "Kenko"),
 ("Altitude of Cusco?", "About 3,400 m", "About 2,000 m", "About 4,500 m", "About 1,000 m"),
 ("The Sacred Valley follows which river?", "The Urubamba", "The Amazon", "The Apurímac", "The Colca"),
 ("Circular terraces in the Sacred Valley thought to be an Inca crop lab?", "Moray", "Maras", "Pisac", "Chinchero"),
 ("Hillside salt pools used since before the Incas?", "Maras", "Moray", "Uyuni", "Paracas"),
 ("Sacred Valley town with a fortress where the Incas beat the Spanish in 1537?", "Ollantaytambo", "Pisac", "Urubamba", "Calca"),
 ("The three Inca sacred animals and their worlds: condor (heavens), puma (earth) and…?", "Snake (underworld)", "Llama (mountains)", "Jaguar (jungle)", "Hummingbird (sky)"),
])
add("Peru", "Machu Picchu", [
 ("Machu Picchu was most likely built as an estate for which emperor?", "Pachacuti", "Atahualpa", "Huáscar", "Manco Inca"),
 ("Roughly when was Machu Picchu built?", "Mid-1400s", "Around 900", "Around 1600", "Around 200 BC"),
 ("Who brought Machu Picchu to world attention in 1911?", "Hiram Bingham", "Howard Carter", "Thor Heyerdahl", "Pizarro"),
 ("Did the Spanish ever find Machu Picchu?", "No, it escaped their destruction", "Yes, they burned it", "Yes, they mined it", "Yes, Pizarro lived there"),
 ("The peak that looms behind the classic Machu Picchu photo?", "Huayna Picchu", "Salkantay", "Ausangate", "Putucusi"),
 ("Machu Picchu was voted one of the New Seven Wonders in…?", "2007", "1983", "1999", "2015"),
 ("What does 'Machu Picchu' mean?", "Old mountain", "Lost city", "Sun gate", "Sacred valley"),
 ("The famous gateway on the Inca Trail with the first view of Machu Picchu?", "Intipunku, the Sun Gate", "The Gate of the Sun at Tiwanaku", "The Puma Gate", "The Condor Gate"),
])
add("Peru", "Huaraz & Cordillera Blanca", [
 ("Highest mountain in Peru?", "Huascarán", "Alpamayo", "Vallunaraju", "Salkantay"),
 ("Huascarán's height?", "About 6,768 m", "About 5,686 m", "About 8,091 m", "About 6,088 m"),
 ("The Cordillera Blanca is the world's highest…?", "Tropical mountain range", "Volcanic range", "Desert range", "Coastal range"),
 ("Vallunaraju's height?", "About 5,686 m", "About 6,768 m", "About 4,600 m", "About 6,088 m"),
 ("Laguna 69 is famous for…?", "Its startling turquoise water under glaciers", "Hot springs", "Pink flamingos", "Being the deepest lake in Peru"),
 ("Which national park holds Laguna 69 and the Santa Cruz trek?", "Huascarán National Park", "Manu", "Colca", "Paracas"),
 ("The 1970 Ancash earthquake triggered an avalanche off Huascarán that buried which town?", "Yungay", "Huaraz", "Caraz", "Chavín"),
 ("Which Cordillera Blanca peak was once voted 'world's most beautiful mountain'?", "Alpamayo", "Huascarán", "Vallunaraju", "Pisco"),
])
add("Peru", "Peru around", [
 ("Capital of Peru?", "Lima", "Cusco", "Arequipa", "Trujillo"),
 ("Peru's best-known beers?", "Cusqueña, Pilsen Callao and Cristal", "Paceña and Huari", "Quilmes and Patagonia", "Aguila and Poker"),
 ("Peru's national cocktail?", "Pisco sour", "Caipirinha", "Mojito", "Fernet con Coca"),
 ("Peru's bright yellow soft drink?", "Inca Kola", "Guaraná", "Cola Real", "Chicha"),
 ("Purple-corn drink popular in Peru?", "Chicha morada", "Api", "Mate de coca", "Horchata"),
 ("Raw fish 'cooked' in lime juice, Peru's national dish?", "Ceviche", "Lomo saltado", "Ají de gallina", "Anticucho"),
 ("Peruvian delicacy, roasted guinea pig?", "Cuy", "Alpaca", "Anticucho", "Chuño"),
 ("Stir-fried beef dish showing Peru's Chinese 'chifa' influence?", "Lomo saltado", "Ceviche", "Causa", "Papa a la huancaína"),
 ("Huacachina is…?", "A desert oasis ringed by giant dunes", "A glacier lake", "An Inca fortress", "A surf town"),
 ("Huacachina sits near which wine and pisco city?", "Ica", "Arequipa", "Nazca", "Paracas"),
 ("Giant ancient lines drawn in the desert of southern Peru?", "The Nazca Lines", "The Paracas Lines", "The Moche Lines", "The Inca Trail"),
 ("Peru's currency?", "Sol", "Peso", "Boliviano", "Real"),
 ("How many potato varieties is Peru said to have?", "Thousands", "About 10", "About 50", "Just 3 native ones"),
 ("Lake shared by Peru and Bolivia, the highest navigable big lake?", "Lake Titicaca", "Lake Poopó", "Laguna Colorada", "Lake Junín"),
])

# ===================== BOLIVIA =====================
add("Bolivia", "La Paz & El Alto", [
 ("Bolivia's constitutional capital?", "Sucre", "La Paz", "Santa Cruz", "Cochabamba"),
 ("Which Bolivian city is the seat of government?", "La Paz", "Sucre", "Potosí", "Oruro"),
 ("La Paz's altitude claim to fame?", "World's highest seat of government", "Lowest capital in Andes", "Highest city in the world", "On the equator"),
 ("La Paz's cable car network?", "Mi Teleférico, the world's largest urban cable car system", "The Metrocable", "Los Ascensores", "Teleférico Sur"),
 ("The huge open-air market in El Alto?", "Feria 16 de Julio", "Mercado de las Brujas", "Feria de Mataderos", "Mercado Central"),
 ("What's sold at La Paz's Witches' Market?", "Dried llama foetuses, potions and charms", "Only tourist souvenirs", "Fresh fish", "Electronics"),
 ("Why are dried llama foetuses buried under new buildings?", "As an offering to Pachamama for luck", "As insulation", "As a building code rule", "To keep rats away"),
 ("The Indigenous women wrestlers of El Alto?", "Cholitas luchadoras", "Las Bravas", "Chicas del ring", "Las Ñustas"),
 ("Bolivia's most common beers?", "Paceña and Huari", "Cusqueña and Pilsen", "Quilmes and Andes", "Cristal and Escudo"),
 ("Bolivia's currency?", "Boliviano", "Sol", "Peso boliviano", "Real"),
 ("Bolivia's first Indigenous president, elected 2005?", "Evo Morales", "Hugo Chávez", "Luis Arce", "Simón Bolívar"),
 ("Bolivia is named after…?", "Simón Bolívar", "A local river", "An Inca emperor", "A Spanish king"),
 ("The famous revolutionary killed in Bolivia in 1967?", "Che Guevara", "Fidel Castro", "Emiliano Zapata", "Pancho Villa"),
 ("Which war cost Bolivia its coastline to Chile?", "The War of the Pacific, 1879–84", "The Chaco War", "The Acre War", "WWI"),
 ("Despite being landlocked, Bolivia still keeps…?", "A navy, training on Lake Titicaca", "A port in Arica", "A merchant fleet in Peru", "A submarine"),
 ("Bolivia's silver city whose Cerro Rico funded the Spanish Empire?", "Potosí", "Oruro", "Sucre", "Tarija"),
])
add("Bolivia", "San Pedro prison", [
 ("San Pedro prison in La Paz is famous because…?", "Inmates buy or rent their cells and families live inside", "It's on an island", "It's the world's oldest prison", "It has no walls"),
 ("Which book tells the story of a British inmate in San Pedro?", "Marching Powder", "Papillon", "Shantaram", "Midnight Express"),
 ("Who wrote Marching Powder?", "Rusty Young", "Gregory David Roberts", "Henri Charrière", "Billy Hayes"),
 ("The British drug trafficker at the heart of Marching Powder?", "Thomas McFadden", "Billy Hayes", "Howard Marks", "Rusty Young"),
 ("What did McFadden famously run inside the prison?", "Tours for backpackers", "A restaurant", "A football league", "A radio station"),
])
add("Bolivia", "Death Road & summits", [
 ("Death Road's official name?", "The North Yungas Road", "Ruta 40", "The Camino Real", "The Carretera Austral"),
 ("Who built Death Road in the 1930s?", "Paraguayan prisoners of war from the Chaco War", "The Incas", "The Spanish", "An American mining company"),
 ("Which organisation called it 'the world's most dangerous road' in 1995?", "The Inter-American Development Bank", "The UN", "Top Gear", "The World Health Organization"),
 ("Why do vehicles drive on the left on Death Road?", "So downhill drivers can see their outer wheels at the cliff edge", "It was built by the British", "Bolivia drives on the left", "To keep trucks against the wall"),
 ("Roughly how far does Death Road drop?", "About 3,500 m", "About 500 m", "About 1,000 m", "About 6,000 m"),
 ("Historically, about how many people died on it each year?", "Around 200–300", "Around 5", "Around 2,000", "Around 30"),
 ("What changed in 2006?", "A new bypass road opened, leaving it mostly to cyclists", "It was paved", "It was closed forever", "Speed cameras were installed"),
 ("Height of Huayna Potosí?", "About 6,088 m", "About 6,768 m", "About 5,686 m", "About 6,962 m"),
 ("Huayna Potosí is in which range?", "The Cordillera Real", "The Cordillera Blanca", "The Cordillera Huayhuash", "The Cordillera Darwin"),
 ("Bolivia's highest mountain?", "Sajama", "Illimani", "Huayna Potosí", "Licancabur"),
 ("The mountain that dominates La Paz's skyline?", "Illimani", "Huayna Potosí", "Sajama", "Chacaltaya"),
 ("Area of the Salar de Uyuni?", "About 10,500 km²", "About 1,000 km²", "About 50,000 km²", "About 300 km²"),
 ("What valuable metal lies under the Salar de Uyuni?", "Lithium", "Gold", "Silver", "Copper"),
])

# ===================== ARGENTINA / CHILE / PATAGONIA =====================
add("Argentina", "Argentina", [
 ("Capital of Argentina?", "Buenos Aires", "Córdoba", "Mendoza", "Rosario"),
 ("Argentina's most common beer?", "Quilmes", "Cristal", "Paceña", "Brahma"),
 ("Argentina's cult drink of Fernet mixed with…?", "Coca-Cola", "Sprite", "Tonic", "Orange juice"),
 ("The herbal drink sipped from a gourd through a metal straw?", "Mate", "Té de coca", "Tereré only", "Chicha"),
 ("The metal straw used for mate?", "Bombilla", "Calabaza", "Pava", "Chupete"),
 ("Argentina's famous grape, especially from Mendoza?", "Malbec", "Carménère", "Tannat", "Merlot"),
 ("Highest mountain in the Americas, near Mendoza?", "Aconcagua", "Ojos del Salado", "Fitz Roy", "Chimborazo"),
 ("Aconcagua's height?", "About 6,961 m", "About 6,088 m", "About 8,091 m", "About 5,895 m"),
 ("Bariloche is famous for…?", "Lakes, skiing and chocolate", "Glaciers and penguins", "Tango and steak", "Wine"),
 ("The world-famous glacier near El Calafate?", "Perito Moreno", "Grey Glacier", "Upsala", "Viedma"),
 ("Argentina's self-styled 'trekking capital', beneath Fitz Roy?", "El Chaltén", "Ushuaia", "El Calafate", "Puerto Madryn"),
 ("The 'southernmost city in the world'?", "Ushuaia", "Punta Arenas", "Puerto Williams", "Río Grande"),
 ("Who's the famous former First Lady, 'Evita'?", "Eva Perón", "Isabel Perón", "Cristina Kirchner", "Mercedes Sosa"),
 ("Argentina's 1982 war with Britain was over which islands?", "The Falklands (Malvinas)", "Tierra del Fuego", "South Georgia only", "Easter Island"),
 ("How many men's World Cups has Argentina won?", "Three: 1978, 1986, 2022", "Two", "Five", "One"),
 ("Buenos Aires's colourful street in La Boca?", "Caminito", "Florida", "Corrientes", "Defensa"),
 ("Famous Buenos Aires cemetery where Evita is buried?", "La Recoleta", "Chacarita", "Père Lachaise", "San Telmo"),
 ("The giant waterfalls on the Argentina–Brazil border?", "Iguazú Falls", "Angel Falls", "Kaieteur", "Gocta"),
 ("Argentine slang for 'cool' or 'great'?", "Copado", "Chévere", "Bacán", "Chido"),
 ("Who's the Argentine-born revolutionary famed in Cuba?", "Che Guevara", "Fidel Castro", "Simón Bolívar", "José de San Martín"),
 ("The hero of Argentine independence who crossed the Andes in 1817?", "José de San Martín", "Simón Bolívar", "Bernardo O'Higgins", "Manuel Belgrano"),
 ("Argentina's famous caramel spread?", "Dulce de leche", "Cajeta only", "Manjar blanco", "Brigadeiro"),
])
add("Chile", "Chile", [
 ("Capital of Chile?", "Santiago", "Valparaíso", "Concepción", "Punta Arenas"),
 ("Chile's most common beers?", "Cristal and Escudo", "Quilmes and Andes", "Cusqueña and Pilsen", "Brahma and Skol"),
 ("Roughly how long is Chile from north to south?", "About 4,300 km", "About 1,000 km", "About 9,000 km", "About 2,000 km"),
 ("Valparaíso is famous for…?", "Colourful hillside houses, street art and funiculars", "Glaciers", "Vineyards only", "Salt flats"),
 ("Valparaíso's hillside funiculars are called…?", "Ascensores", "Teleféricos", "Tranvías", "Cables"),
 ("Which Nobel-winning poet had a house, La Sebastiana, in Valparaíso?", "Pablo Neruda", "Gabriela Mistral", "Jorge Luis Borges", "Gabriel García Márquez"),
 ("The driest non-polar desert on Earth, in northern Chile?", "The Atacama", "The Sechura", "The Gobi", "The Namib"),
 ("Torres del Paine's three granite towers sit in which region?", "Chilean Patagonia", "Argentine Patagonia", "The Atacama", "The Lake District"),
 ("Chile's remote Pacific island with the moai statues?", "Easter Island (Rapa Nui)", "Robinson Crusoe Island", "Chiloé", "Galápagos"),
 ("The 1973 coup brought which dictator to power in Chile?", "Augusto Pinochet", "Juan Perón", "Alfredo Stroessner", "Hugo Banzer"),
 ("Chilean slang for 'you know?' or 'got it?'", "¿Cachai?", "¿Viste?", "¿Me entiendes, pues?", "¿Vale?"),
 ("Chile and Peru both claim which spirit as their own?", "Pisco", "Tequila", "Cachaça", "Rum"),
 ("Chile's long scenic road through Patagonia?", "Carretera Austral", "Ruta 40", "Pan-American Highway", "Ruta 3"),
])
add("Patagonia", "Pumas & jaguars", [
 ("Where's the best place in the world to see wild pumas?", "Torres del Paine, Chile", "The Amazon", "Yellowstone", "The Atacama"),
 ("The puma, cougar and mountain lion are…?", "The same species", "Three different cats", "Two species", "Hybrids"),
 ("Can pumas roar?", "No, they purr, hiss and scream", "Yes, louder than lions", "Only males", "Only at night"),
 ("Largest cat in the Americas?", "The jaguar", "The puma", "The ocelot", "The lynx"),
 ("How does a jaguar often kill its prey?", "A bite straight through the skull", "Strangling with its tail", "Chasing to exhaustion", "Poison"),
 ("Jaguars, unusually for big cats, love…?", "Water and swimming", "Snow", "Climbing cliffs", "Living in groups"),
 ("A puma's main prey in Patagonia?", "Guanacos", "Penguins", "Llamas only", "Condors"),
 ("Wild relative of the llama common in Patagonia?", "Guanaco", "Alpaca", "Vicuña only", "Huemul"),
 ("Wingspan of the Andean condor?", "Up to about 3.3 m", "About 1 m", "About 6 m", "About 2 m"),
 ("Jaguars' spots have dots inside them. These rosettes are…?", "Bigger and fewer than a leopard's", "Identical to a leopard's", "Stripes", "Missing on males"),
])

# ===================== AMAZON =====================
add("Amazon", "Amazon", [
 ("Roughly how big is the Amazon rainforest?", "About 5.5 million km²", "About 500,000 km²", "About 20 million km²", "About 1 million km²"),
 ("How many countries share the Amazon rainforest?", "9", "3", "12", "5"),
 ("Which country holds about 60% of the Amazon?", "Brazil", "Peru", "Colombia", "Bolivia"),
 ("Roughly what share of all fresh water flowing into the world's oceans comes from the Amazon River?", "About 20%", "About 2%", "About 50%", "About 5%"),
 ("Roughly how many trees are in the Amazon?", "About 390 billion", "About 1 billion", "About 10 trillion", "About 50 million"),
 ("About what share of the world's known species live in the Amazon?", "About 10%", "About 1%", "About 50%", "About 90%"),
 ("The Amazon's famous pink freshwater dolphin?", "Boto", "Vaquita", "Tucuxi", "Baiji"),
 ("Largest rodent in the world, found in the Amazon?", "Capybara", "Agouti", "Paca", "Beaver"),
 ("The world's heaviest snake, found in Amazon rivers?", "Green anaconda", "Reticulated python", "Boa constrictor", "King cobra"),
 ("The giant Amazon fish that breathes air?", "Arapaima (paiche)", "Piranha", "Tambaqui", "Peacock bass"),
 ("Amazon tree-dwellers that move so slowly algae grows on their fur?", "Sloths", "Howler monkeys", "Kinkajous", "Tamanduas"),
 ("What do the Amazon's tiny, bright 'poison dart' frogs warn predators with?", "Their bright colours", "Loud croaks", "Spikes", "Bad smell"),
 ("Where the Rio Negro and Solimões meet without mixing for kilometres?", "The Meeting of the Waters, near Manaus", "Iquitos", "Leticia", "Belém"),
 ("Bolivia's gateway town to the Amazon and Madidi?", "Rurrenabaque", "Trinidad", "Cobija", "Riberalta"),
])

# ===================== COLOMBIA =====================
add("Colombia", "Colombia", [
 ("Capital of Colombia?", "Bogotá", "Medellín", "Cartagena", "Cali"),
 ("Colombia's most common beers?", "Aguila, Poker and Club Colombia", "Cristal and Pilsen", "Quilmes and Andes", "Paceña"),
 ("Colombia's big hearty platter from the Medellín region?", "Bandeja paisa", "Ajiaco", "Sancocho", "Lechona"),
 ("Medellín's once-dangerous neighbourhood now famous for graffiti tours and outdoor escalators?", "Comuna 13", "El Poblado", "Laureles", "Envigado"),
 ("Colombian Nobel winner who wrote One Hundred Years of Solitude?", "Gabriel García Márquez", "Pablo Neruda", "Mario Vargas Llosa", "Isabel Allende"),
 ("Colombian slang for 'cool'?", "Chévere / bacano", "Copado", "Bacán only", "Guay"),
 ("Colombian slang 'parce' means…?", "Mate, buddy", "Party", "Money", "Beer"),
 ("Colombia's famous coffee-growing region?", "The Eje Cafetero (Coffee Triangle)", "The Llanos", "La Guajira", "Chocó"),
 ("The independence hero, born in Caracas, who liberated Colombia?", "Simón Bolívar", "San Martín", "O'Higgins", "Sucre"),
 ("The Caribbean coast's mountains, highest coastal range on Earth?", "Sierra Nevada de Santa Marta", "Serranía del Baudó", "Los Nevados", "Cordillera Oriental"),
 ("Colombia is the world's top source of which gemstone?", "Emeralds", "Diamonds", "Rubies", "Opals"),
])
add("Colombia", "Pablo Escobar", [
 ("Which cartel did Pablo Escobar lead?", "The Medellín Cartel", "The Cali Cartel", "The Sinaloa Cartel", "Los Zetas"),
 ("Escobar's notorious offer: 'plata o plomo' meant…?", "Take a bribe or take a bullet", "Silver or gold", "Pay or leave", "Money or land"),
 ("What was the prison Escobar built for himself called?", "La Catedral", "El Palacio", "La Fortaleza", "San Pedro"),
 ("When was Escobar killed?", "2 December 1993", "1989", "2001", "1985"),
 ("Where was Escobar shot?", "On a rooftop in Medellín", "In the jungle", "In Bogotá's airport", "At his ranch"),
 ("Escobar's ranch that left Colombia with a growing population of…?", "Hippos, at Hacienda Nápoles", "Lions", "Elephants", "Giraffes"),
 ("Which magazine listed Escobar among the world's billionaires?", "Forbes", "Time", "Fortune", "The Economist"),
 ("The hit Netflix series about the hunt for Escobar?", "Narcos", "Breaking Bad", "El Chapo", "Ozark"),
 ("Which group of victims' families waged a violent campaign against Escobar?", "Los Pepes", "FARC", "Los Extraditables", "The Cali Cartel alone"),
 ("What did Escobar's group, 'Los Extraditables', fight above all?", "Extradition to the United States", "Higher taxes", "The Catholic Church", "Land reform"),
])

# ===================== BRAZIL =====================
add("Brazil", "Brazil", [
 ("Capital of Brazil?", "Brasília", "Rio de Janeiro", "São Paulo", "Salvador"),
 ("When did Brasília become the capital?", "1960", "1889", "1822", "1985"),
 ("Architect behind Brasília's modernist buildings and Rio's Sambadrome?", "Oscar Niemeyer", "Lúcio Costa alone", "Le Corbusier", "Gaudí"),
 ("Brazil's language?", "Portuguese", "Spanish", "Brazilian", "Tupi"),
 ("Brazil's most common beers?", "Brahma, Skol and Antarctica", "Quilmes and Isenbeck", "Cristal and Escudo", "Aguila and Poker"),
 ("Brazil's national cocktail, made with cachaça?", "Caipirinha", "Mojito", "Pisco sour", "Batida"),
 ("Brazil's national dish, a black bean and pork stew?", "Feijoada", "Moqueca", "Churrasco", "Coxinha"),
 ("Largest city in South America?", "São Paulo", "Buenos Aires", "Rio de Janeiro", "Lima"),
 ("Christ the Redeemer was completed in…?", "1931", "1900", "1955", "1888"),
 ("Christ the Redeemer stands on which mountain?", "Corcovado", "Sugarloaf", "Pedra da Gávea", "Tijuca Peak"),
 ("Where do Rio's samba schools parade during Carnival?", "The Sambadrome", "Copacabana beach", "Maracanã", "Lapa"),
 ("Florianópolis is mostly on…?", "An island, Santa Catarina", "A peninsula in Bahia", "The Amazon", "A lake"),
 ("Brazil's World Cup tally?", "5 titles", "3 titles", "4 titles", "6 titles"),
 ("Which Brazilian surfer won Olympic gold in 2021?", "Italo Ferreira", "Gabriel Medina", "Filipe Toledo", "Adriano de Souza"),
 ("Brazil's wave of world-champion surfers is nicknamed…?", "The Brazilian Storm", "The Samba Squad", "The Green Wave", "The Rio Crew"),
 ("Three-time world surfing champion Gabriel Medina is from…?", "Brazil", "Portugal", "Australia", "Hawaii"),
 ("The WSL's Brazil event is usually held at which beach?", "Saquarema (Itaúna)", "Copacabana", "Ipanema", "Praia Mole"),
 ("Brazil was a colony of which country?", "Portugal", "Spain", "France", "The Netherlands"),
 ("Brazil's currency?", "Real", "Peso", "Cruzeiro", "Escudo"),
 ("Brazil was the last country in the Americas to abolish slavery, in…?", "1888", "1822", "1865", "1910"),
 ("The Brazilian martial art disguised as dance?", "Capoeira", "Jiu-jitsu", "Samba", "Frevo"),
])

# ===================== MEXICO & CENTRAL AMERICA =====================
add("Mexico", "Aztecs & pyramids", [
 ("The Aztec capital, built on a lake island in 1325?", "Tenochtitlan", "Teotihuacan", "Chichén Itzá", "Tula"),
 ("What sign told the Aztecs where to build their capital?", "An eagle on a cactus eating a snake", "A jaguar on a rock", "A falling star", "A white deer"),
 ("Where does that eagle-cactus-snake image appear today?", "On Mexico's flag", "On the peso coin only", "On Peru's flag", "Nowhere"),
 ("Modern city built on top of Tenochtitlan?", "Mexico City", "Guadalajara", "Puebla", "Oaxaca"),
 ("Spanish conquistador who toppled the Aztecs in 1521?", "Hernán Cortés", "Francisco Pizarro", "Pedro de Alvarado", "Balboa"),
 ("Aztec emperor when Cortés arrived?", "Moctezuma II", "Cuauhtémoc", "Atahualpa", "Itzcóatl"),
 ("Language of the Aztecs, still spoken by over a million Mexicans?", "Nahuatl", "Quechua", "Maya", "Zapotec"),
 ("Everyday English words from Nahuatl?", "Chocolate, tomato, avocado, chilli", "Llama, puma, condor", "Canoe, hammock", "Kayak, parka"),
 ("The Aztec sun and war god, fed with human sacrifice?", "Huitzilopochtli", "Inti", "Kukulkan", "Viracocha"),
 ("The feathered serpent god?", "Quetzalcoatl", "Tlaloc", "Huitzilopochtli", "Xipe Totec"),
 ("Ancient city near Mexico City with the Pyramids of the Sun and Moon?", "Teotihuacan", "Chichén Itzá", "Tulum", "Palenque"),
 ("Did the Aztecs build Teotihuacan?", "No, it was already ancient ruins to them", "Yes, in 1400", "Yes, as their capital", "Yes, with Spanish help"),
 ("Teotihuacan's main avenue?", "The Avenue of the Dead", "The Avenue of Sphinxes", "The Sacred Way", "The Sun Road"),
 ("The step pyramid of El Castillo is at which Maya site?", "Chichén Itzá", "Teotihuacan", "Tikal", "Copán"),
 ("What happens at El Castillo at the equinoxes?", "Shadows form a serpent sliding down the stairs", "The sun sets through the top", "Water fills the steps", "Bells ring inside"),
 ("Which pyramid has the largest volume of any in the world?", "The Great Pyramid of Cholula, Mexico", "The Great Pyramid of Giza", "The Pyramid of the Sun", "El Castillo"),
 ("Which civilisation built Chichén Itzá, Tikal and Palenque?", "The Maya", "The Aztecs", "The Olmecs", "The Incas"),
 ("The 'mother culture' of Mexico famed for giant stone heads?", "The Olmecs", "The Toltecs", "The Zapotecs", "The Maya"),
])
add("Mexico", "Mexico around", [
 ("Capital of Mexico?", "Mexico City", "Guadalajara", "Monterrey", "Cancún"),
 ("Mexico's best-known beers?", "Corona, Modelo, Tecate and Dos Equis", "Quilmes and Patagonia", "Brahma and Skol", "Gallo and Imperial"),
 ("Tequila must come from which plant?", "Blue agave", "Any agave", "Sugar cane", "Corn"),
 ("Tequila mainly comes from which state?", "Jalisco", "Oaxaca", "Yucatán", "Sonora"),
 ("Mexico's smoky agave spirit, especially from Oaxaca?", "Mezcal", "Pulque", "Sotol", "Raicilla"),
 ("Spit-roasted pork tacos, brought by Lebanese immigrants?", "Tacos al pastor", "Carnitas", "Barbacoa", "Cochinita"),
 ("The festival honouring the dead on 1–2 November?", "Día de los Muertos", "Las Posadas", "Cinco de Mayo", "Semana Santa"),
 ("Cinco de Mayo marks a victory over which country?", "France, at Puebla in 1862", "Spain", "The USA", "Britain"),
 ("Mexico has the largest population of…?", "Spanish speakers in the world", "Catholics in Asia", "Portuguese speakers", "English speakers in Latin America"),
 ("The Mexican painter famous for self-portraits with a unibrow?", "Frida Kahlo", "Diego Rivera", "Rufino Tamayo", "Remedios Varo"),
])
add("Central America", "Guatemala", [
 ("Capital of Guatemala?", "Guatemala City", "Antigua", "Flores", "Quetzaltenango"),
 ("Guatemala's currency is named after which bird?", "The quetzal", "The toucan", "The macaw", "The condor"),
 ("Guatemala's most common beer?", "Gallo", "Imperial", "Toña", "Corona"),
 ("The colonial former capital ringed by volcanoes?", "Antigua", "Flores", "Panajachel", "Cobán"),
 ("The hike where you camp watching the next-door volcano erupt?", "Acatenango, facing Fuego", "Pacaya", "Tajumulco", "Agua"),
 ("Lake ringed by volcanoes that Aldous Huxley called the world's most beautiful?", "Lake Atitlán", "Lake Izabal", "Lake Petén Itzá", "Lake Nicaragua"),
 ("Giant Maya city deep in Guatemala's jungle?", "Tikal", "Copán", "Palenque", "Caracol"),
])
add("Central America", "Nicaragua", [
 ("Capital of Nicaragua?", "Managua", "Granada", "León", "San Juan del Sur"),
 ("Nicaragua's most common beers?", "Toña and Victoria", "Gallo and Moza", "Imperial and Pilsen", "Panamá and Atlas"),
 ("Nicaragua's famous rum?", "Flor de Caña", "Havana Club", "Ron Zacapa", "Bacardí"),
 ("Where can you go 'volcano boarding'?", "Cerro Negro, near León", "Masaya", "Momotombo", "Concepción"),
 ("The island in Lake Nicaragua made of two volcanoes?", "Ometepe", "Little Corn", "Zapatera", "Isla de Pascua"),
 ("Nicaragua's currency?", "Córdoba", "Colón", "Lempira", "Quetzal"),
 ("Nicaragua's national dish, also claimed by Costa Rica?", "Gallo pinto", "Pupusas", "Baleadas", "Casado"),
])
add("Central America", "Costa Rica", [
 ("Capital of Costa Rica?", "San José", "Liberia", "Limón", "Alajuela"),
 ("Costa Rica's national catchphrase?", "Pura vida", "Tranquilo", "Hakuna matata", "Qué chévere"),
 ("What did Costa Rica abolish in 1948?", "Its army", "Its monarchy", "Its currency", "Its taxes"),
 ("Costa Rica's most common beer?", "Imperial", "Toña", "Gallo", "Corona"),
 ("Roughly what share of the world's biodiversity is in Costa Rica?", "About 5–6%", "About 0.1%", "About 25%", "About 1%"),
 ("Costa Rica's famous cone volcano near La Fortuna?", "Arenal", "Poás", "Irazú", "Rincón de la Vieja"),
 ("Costa Rica's currency?", "Colón", "Córdoba", "Dollar only", "Peso"),
])
