from facts6 import F, add
# Mind & memory: the science behind how Cerebrito trains you. Knowing why a method works makes
# people far more likely to stick with it. Rows carry an 8th field: the explanation shown after answering.

add("Mind", "How memory works", [
 ("What's the 'forgetting curve'?", "Memory fades fast, then slower", "Memory fades at a steady rate", "Memory never really fades", "Memory fades only in old age",
  "Hermann Ebbinghaus found in 1885 that most forgetting happens in the first hours and days, then levels off. Reviewing at the right moment resets the curve."),
 ("Who first measured the forgetting curve, by memorising nonsense syllables?", "Hermann Ebbinghaus", "Sigmund Freud", "William James", "Ivan Pavlov",
  "Ebbinghaus tested himself on thousands of syllables like 'DAX' and 'BUP' so meaning couldn't help, and charted how fast they faded."),
 ("The spacing effect says you remember more when study is…?", "Spread out over time", "Crammed into one session", "Done late at night", "Done with music",
  "The same total study time spread over days beats one long session, often by a wide margin. It's one of the most reliable findings in psychology."),
 ("The 'testing effect' (retrieval practice) says the best way to learn is…?", "Recalling it from memory", "Re-reading your notes", "Highlighting key lines", "Copying it out neatly",
  "Pulling an answer out of memory strengthens it far more than reviewing it again. That's why Cerebrito asks you questions instead of showing facts."),
 ("Why does struggling to recall something help you learn it?", "Effort strengthens the memory", "It doesn't, ease is better", "It releases melatonin", "It shrinks the hippocampus",
  "Psychologists call these 'desirable difficulties': retrieval that takes effort, but succeeds, leaves a stronger trace than easy recognition."),
 ("Why is re-reading a weak way to study?", "Familiarity feels like knowing", "It wastes paper", "It damages eyesight", "It causes forgetting",
  "Text you've seen feels familiar, which creates an illusion of mastery. Testing yourself reveals what you can actually recall."),
 ("Interleaving means…?", "Mixing different topics in one session", "Studying one topic until perfect", "Studying only at night", "Studying two languages at once",
  "Mixing problem types forces you to work out which approach fits each one. It feels harder but improves long-term learning and transfer."),
 ("Which brain structure is vital for forming new long-term memories of facts and events?", "The hippocampus", "The cerebellum", "The brainstem", "The occipital lobe",
  "The hippocampus binds new experiences into memories, then gradually hands them to the cortex for long-term storage."),
 ("Patient H.M. couldn't form new long-term memories after surgery removed parts of his…?", "Hippocampi", "Frontal lobes", "Cerebellum", "Amygdala",
  "After 1953 surgery for epilepsy, Henry Molaison could hold a conversation but forgot it minutes later. He could still learn new motor skills, revealing separate memory systems."),
 ("Roughly how many items can working memory hold at once?", "About four", "About forty", "About one", "Unlimited",
  "Miller's famous 'seven, plus or minus two' has been revised down: modern estimates put it at about four chunks. That's why chunking helps."),
 ("'Chunking' helps memory by…?", "Grouping items into units", "Splitting words into letters", "Repeating out loud", "Writing in capitals",
  "0412555918 is hard; 0412 555 918 is easy. Grouping turns many items into a few meaningful chunks that fit working memory."),
 ("The 'memory palace' technique uses…?", "Imagined places along a route", "Rhythms and songs", "Coloured notes", "Repeating at bedtime",
  "The method of loci, used since ancient Greece: place vivid images at spots along a familiar route, then walk it in your mind to recall them."),
 ("Memory champions mostly have…?", "Ordinary brains, trained technique", "Photographic memories", "Larger hippocampi at birth", "Higher IQs than everyone",
  "Brain scans show champions' brains aren't special. They use techniques like memory palaces, and ordinary people trained for six weeks improved dramatically."),
 ("The 'generation effect' says you remember better what you…?", "Produce yourself", "Read in bold", "Hear twice", "See in a list",
  "Filling in a missing word or creating your own example makes it stick better than reading the complete version."),
 ("Explaining an idea to someone else improves your own memory because…?", "You have to rebuild it yourself", "Talking raises dopamine", "It's simply repetition", "It doesn't",
  "Teaching forces you to retrieve, organise and fill gaps, which is why the 'protégé effect' boosts the teacher's learning."),
])
add("Mind", "Sleep and the brain", [
 ("When does the brain consolidate much of what you learned that day?", "During sleep", "During exercise", "Right after meals", "Only while awake",
  "Overnight the hippocampus replays the day's patterns, moving them toward long-term storage in the cortex. Sleep after learning protects it."),
 ("Pulling an all-nighter before an exam mainly hurts…?", "Storing what you studied", "Your eyesight", "Your vocabulary", "Nothing, it helps",
  "Without sleep the hippocampus can't consolidate the day, and it's worse at taking in new memories the next day too."),
 ("Napping after learning tends to…?", "Help the learning stick", "Erase it", "Have no effect", "Only help children",
  "Even a short nap with some deep sleep can protect fresh memories. Long naps late in the day can hurt night-time sleep, though."),
])
add("Mind", "A changing brain", [
 ("'Neuroplasticity' means…?", "The brain rewires with experience", "The brain is made of plastic", "Brain cells never change", "The brain shrinks with use",
  "Connections between neurons strengthen, weaken and reorganise with use throughout life. Training works because the brain adapts."),
 ("'Neurons that fire together…'", "…wire together", "…tire together", "…expire together", "…retire together",
  "A summary of Donald Hebb's 1949 idea: when neurons repeatedly activate together, the connection between them strengthens."),
 ("Can adults grow new neurons?", "Yes, in some regions", "No, never after birth", "Only before age 10", "Only in the spine",
  "Evidence suggests new neurons form in the adult hippocampus, though how much in humans is debated. Exercise appears to boost it."),
 ("London taxi drivers who learned 'the Knowledge' showed a larger…?", "Hippocampus region", "Cerebellum", "Visual cortex", "Brainstem",
  "Eleanor Maguire's studies found the rear hippocampus grew as trainees memorised London's 25,000 streets, a famous case of adult plasticity."),
 ("Which habit has the strongest evidence for protecting the ageing brain?", "Regular aerobic exercise", "Daily crosswords alone", "Fish oil alone", "Listening to Mozart",
  "Exercise raises BDNF, a growth factor for neurons, improves blood flow and is linked to a bigger hippocampus and lower dementia risk."),
 ("BDNF, boosted by exercise, is often described as…?", "Fertiliser for neurons", "A sleep hormone", "A stress hormone", "A type of fat",
  "Brain-derived neurotrophic factor supports neuron growth and new connections. Exercise is one of the most reliable ways to raise it."),
 ("The 'Mozart effect' that music makes babies smarter is…?", "Mostly a myth", "Proven by many studies", "True only for violin", "True only for adults",
  "A 1993 study found a brief boost in one spatial task in students. It never showed lasting intelligence gains, and later studies largely failed to replicate it."),
 ("Do we use only 10% of our brains?", "No, it's a myth", "Yes, exactly 10%", "Only while asleep", "Only children use more",
  "Brain scans show activity across virtually all regions over a day, and damage to almost any area causes problems."),
 ("Brain training transfers best to…?", "Tasks closely like the training", "Every skill you have", "IQ, by 20 points", "Nothing at all",
  "Training improves the trained skill and close relatives most. That's why Cerebrito trains many different skills plus real knowledge."),
])
add("Mind", "Attention and focus", [
 ("Is multitasking efficient for the brain?", "No, it rapidly switches", "Yes, it runs tasks in parallel", "Only for women", "Only with caffeine",
  "For tasks that need attention, the brain switches back and forth, paying a 'switch cost' each time. Errors rise and speed falls."),
 ("The 'Stroop effect' shows that…?", "Reading is hard to switch off", "Colours are easy to name", "Blue is the fastest colour", "Words are read right to left",
  "Naming the ink colour of 'RED' printed in blue is slow because reading is automatic. Cerebrito's Ink game trains overriding it."),
 ("The 'cocktail party effect' is…?", "Hearing your name in a noisy room", "Getting tipsy faster in a crowd", "Forgetting names at parties", "Talking louder in noise",
  "Your brain filters out most background chatter but still monitors it, so your own name can break through."),
 ("Your 'default mode network' is most active when you…?", "Let your mind wander", "Do hard maths", "Lift weights", "Sleep deeply",
  "It's a set of brain regions active during daydreaming, remembering and imagining the future, and quieter during focused tasks."),
 ("In the famous 'invisible gorilla' study, about how many viewers missed the gorilla?", "About half", "Almost none", "Everyone", "About 5%",
  "Asked to count basketball passes, about half of viewers never noticed a person in a gorilla suit walking through. Attention is narrow."),
])
