from facts3 import F, add

# ===================== GREAT LEADERS =====================
add("History", "Alexander the Great", [
 ("Where was Alexander the Great born, in 356 BC?", "Pella, Macedon", "Athens", "Sparta", "Babylon"),
 ("Who tutored the young Alexander?", "Aristotle", "Plato", "Socrates", "Pythagoras"),
 ("Alexander's father?", "Philip II of Macedon", "Darius III", "Leonidas", "Pericles"),
 ("How old was Alexander when he became king?", "20", "12", "35", "16"),
 ("Alexander's famous horse?", "Bucephalus", "Pegasus", "Incitatus", "Marengo"),
 ("Which Persian king did Alexander defeat at Issus and Gaugamela?", "Darius III", "Xerxes", "Cyrus the Great", "Artaxerxes"),
 ("How did Alexander 'solve' the Gordian Knot?", "Cut it with his sword", "Untied it patiently", "Burned it", "Gave up"),
 ("How far east did Alexander's army march before turning back?", "Into India, to the Beas River", "To China", "Only to Egypt", "To Japan"),
 ("Did Alexander ever lose a battle he commanded?", "No", "Yes, at Gaugamela", "Yes, in India", "Yes, in Egypt"),
 ("Where and at what age did Alexander die?", "Babylon, aged 32", "Athens, aged 50", "Alexandria, aged 40", "India, aged 25"),
 ("Which Homeric hero did Alexander idolise, honouring his tomb at Troy?", "Achilles", "Hercules", "Odysseus", "Agamemnon"),
])
add("History", "Genghis Khan", [
 ("Genghis Khan's birth name?", "Temüjin", "Kublai", "Ögedei", "Tolui"),
 ("In what year was Temüjin proclaimed Genghis Khan?", "1206", "1066", "1453", "1279"),
 ("The Mongol Empire became the largest…in history?", "Contiguous land empire", "Sea empire", "Empire by population", "Empire by duration"),
 ("The Mongol relay-station postal system?", "The Yam", "The Chasqui", "The Silk Post", "The Cursus"),
 ("What made Mongol armies so deadly?", "Mounted archers, speed and discipline", "Gunpowder cannons", "War elephants", "Heavy armour"),
 ("When did Genghis Khan die?", "1227", "1206", "1294", "1162"),
 ("What's still unknown about Genghis Khan?", "Where he's buried", "His birth name", "His sons' names", "His country"),
 ("Which grandson founded China's Yuan dynasty?", "Kublai Khan", "Batu Khan", "Hulagu", "Timur"),
 ("Which Venetian traveller served at Kublai Khan's court?", "Marco Polo", "Christopher Columbus", "Ibn Battuta", "Vasco da Gama"),
 ("Genghis Khan's empire made which trade route safe again?", "The Silk Road", "The Spice Route", "The Amber Road", "The Inca Road"),
])
add("History", "Napoleon", [
 ("Where was Napoleon born?", "Corsica", "Paris", "Sardinia", "Elba"),
 ("When did Napoleon crown himself Emperor?", "1804", "1789", "1815", "1799"),
 ("Napoleon's greatest victory, in 1805?", "Austerlitz", "Waterloo", "Trafalgar", "Borodino"),
 ("The 1812 campaign that wrecked Napoleon's Grande Armée?", "The invasion of Russia", "The Egypt campaign", "Trafalgar", "The Peninsular War"),
 ("Napoleon's first exile island?", "Elba", "Saint Helena", "Corsica", "Malta"),
 ("Napoleon's comeback after escaping Elba is called…?", "The Hundred Days", "The Restoration", "The Long March", "The Return"),
 ("Who beat Napoleon at Waterloo in 1815?", "Wellington and Blücher", "Nelson", "Kutuzov alone", "Metternich"),
 ("Where did Napoleon die in 1821?", "Saint Helena", "Elba", "Paris", "Moscow"),
 ("Napoleon's lasting legal legacy?", "The Napoleonic Code", "The Magna Carta", "The Geneva Convention", "The metric second"),
 ("Was Napoleon unusually short?", "No, about average height for his time", "Yes, about 150 cm", "Yes, the shortest French ruler", "He was a giant"),
 ("What did Napoleon sell to the US in 1803?", "The Louisiana Territory", "Florida", "Quebec", "Texas"),
 ("Which artefact did Napoleon's Egypt expedition discover?", "The Rosetta Stone", "Tutankhamun's tomb", "The Sphinx", "Cleopatra's needle"),
])
add("History", "Other great leaders", [
 ("Which Carthaginian general crossed the Alps with elephants in 218 BC?", "Hannibal", "Scipio", "Hamilcar", "Pyrrhus"),
 ("The Persian king who founded the Achaemenid Empire and freed the Jews of Babylon?", "Cyrus the Great", "Darius I", "Xerxes", "Cambyses"),
 ("Who was crowned Emperor of the Romans on Christmas Day, 800?", "Charlemagne", "Otto the Great", "Clovis", "Constantine"),
 ("The Muslim sultan who retook Jerusalem from the Crusaders in 1187?", "Saladin", "Suleiman", "Mehmed II", "Baibars"),
 ("The Ottoman sultan who captured Constantinople in 1453?", "Mehmed II", "Suleiman", "Osman I", "Selim I"),
 ("Who unified China in 221 BC as its first emperor?", "Qin Shi Huang", "Kublai Khan", "Mao Zedong", "Liu Bang"),
 ("Who led Britain through most of WWII?", "Winston Churchill", "Neville Chamberlain", "Clement Attlee", "Anthony Eden"),
 ("The Spartan king who held Thermopylae with 300 Spartans in 480 BC?", "Leonidas", "Lysander", "Pericles", "Xerxes"),
 ("The Mongol-Turkic conqueror Timur is better known in English as…?", "Tamerlane", "Attila", "Saladin", "Babur"),
 ("The 'Scourge of God' who led the Huns?", "Attila", "Genghis Khan", "Alaric", "Timur"),
 ("The Zulu king whose army reshaped southern Africa in the 1820s?", "Shaka", "Cetshwayo", "Mansa Musa", "Menelik II"),
 ("The 14th-century Mali emperor often called the richest person in history?", "Mansa Musa", "Sundiata", "Haile Selassie", "Ramses II"),
])
add("History", "Alan Turing & Enigma", [
 ("Where did Alan Turing work to break Enigma?", "Bletchley Park", "MI6 headquarters", "Cambridge University", "Royal Navy HQ"),
 ("The electromechanical machine Turing designed to crack Enigma settings?", "The Bombe", "Colossus", "The Difference Engine", "ENIAC"),
 ("What was the Bombe called in the film The Imitation Game?", "Christopher", "Victory", "Alan", "Enigma"),
 ("Who played Turing in The Imitation Game (2014)?", "Benedict Cumberbatch", "Eddie Redmayne", "Tom Hardy", "Matt Smith"),
 ("Which country's codebreakers cracked early Enigma first and shared it with Britain?", "Poland", "France", "Czechoslovakia", "The USA"),
 ("Enigma intelligence was code-named…?", "Ultra", "Magic", "Overlord", "Purple"),
 ("Historians estimate codebreaking shortened the war by about…?", "Two years", "Two weeks", "Ten years", "It made no difference"),
 ("Turing's famous test for machine intelligence (1950)?", "The Turing test", "The Enigma test", "The Bletchley test", "The Lovelace test"),
 ("What happened to Turing in 1952?", "Prosecuted for homosexuality and chemically castrated", "Knighted", "Made head of MI6", "Moved to America"),
 ("When did Turing receive a royal pardon?", "2013", "1954", "1990", "2021"),
 ("Whose face is on the Bank of England £50 note since 2021?", "Alan Turing", "Winston Churchill", "Charles Darwin", "Isaac Newton"),
 ("What was Enigma's key weakness that codebreakers exploited?", "A letter could never encrypt to itself", "It used only 10 letters", "Its settings never changed", "It was made in Britain"),
])

# ===================== SAMURAI / JAPAN / CHINA =====================
add("Japan", "Samurai & katana", [
 ("The samurai code of honour?", "Bushido", "Shinto", "Zen", "Kaizen"),
 ("A samurai without a master was a…?", "Ronin", "Ninja", "Shogun", "Daimyo"),
 ("The paired swords a samurai wore, katana and wakizashi?", "Daishō", "Tantō", "Naginata", "Yari"),
 ("The special steel smelted for katanas?", "Tamahagane", "Damascus", "Wootz", "Toledo"),
 ("Why do katanas have a curve and a wavy line, the hamon?", "Clay-coated differential hardening: hard edge, flexible spine", "They're bent by hand after forging", "The steel is twisted", "It's purely decorative engraving"),
 ("Why was katana steel folded many times?", "To even out impurities and carbon in poor-quality iron", "To make it lighter", "To add a pattern only", "To make it magnetic"),
 ("Ritual suicide by disembowelment?", "Seppuku", "Kamikaze", "Harakiri tea", "Bushido"),
 ("The undefeated swordsman who wrote The Book of Five Rings?", "Miyamoto Musashi", "Oda Nobunaga", "Hattori Hanzo", "Sasaki Kojiro"),
 ("The 1600 battle that put the Tokugawa in power?", "Sekigahara", "Nagashino", "Okehazama", "Dan-no-ura"),
 ("The shogun who founded the Tokugawa shogunate?", "Tokugawa Ieyasu", "Oda Nobunaga", "Toyotomi Hideyoshi", "Minamoto no Yoritomo"),
 ("The African man who became a samurai under Oda Nobunaga?", "Yasuke", "Musashi", "Hanzo", "Ieyasu"),
 ("What ended the samurai class in the 1870s?", "The Meiji Restoration's reforms", "WWII", "A plague", "An American invasion"),
 ("Samurai leader of the 1877 Satsuma Rebellion, inspiration for The Last Samurai?", "Saigō Takamori", "Tokugawa Ieyasu", "Musashi", "Katsumoto"),
 ("The 47 Ronin are famous for…?", "Avenging their master, then committing seppuku", "Defeating the Mongols", "Founding Tokyo", "Building Osaka Castle"),
 ("Which typhoons destroyed Mongol invasion fleets in 1274 and 1281?", "The kamikaze, 'divine winds'", "The tsunami of Edo", "The Great Storm", "Nobunaga's fire"),
])
add("Japan", "Japan", [
 ("Capital of Japan?", "Tokyo", "Kyoto", "Osaka", "Hiroshima"),
 ("Japan's capital for over 1,000 years before Tokyo?", "Kyoto", "Nara", "Osaka", "Kamakura"),
 ("Height of Mount Fuji?", "3,776 m", "2,500 m", "4,800 m", "6,000 m"),
 ("Japan's bullet train first ran in…?", "1964", "1980", "1945", "2000"),
 ("Japan's currency?", "Yen", "Yuan", "Won", "Ringgit"),
 ("Hiroshima was bombed on 6 August 1945. Nagasaki on…?", "9 August 1945", "15 August 1945", "1 September 1945", "6 August as well"),
 ("Japan's big beer brands?", "Asahi, Kirin, Sapporo and Suntory", "Tsingtao", "Hite and Cass", "Singha"),
 ("Japan's native religion of kami spirits?", "Shinto", "Zen", "Bushido", "Taoism"),
 ("Japan's imperial house is famous as…?", "The oldest continuous hereditary monarchy", "The newest monarchy", "An elected monarchy", "Abolished in 1945"),
 ("Roughly how many islands make up Japan?", "About 14,000", "4", "About 200", "About 1,000"),
 ("The Japanese practice of 'forest bathing'?", "Shinrin-yoku", "Ikigai", "Kaizen", "Wabi-sabi"),
])
add("China", "China", [
 ("Capital of China?", "Beijing", "Shanghai", "Xi'an", "Hong Kong"),
 ("Which city is home to the Terracotta Army?", "Xi'an", "Beijing", "Nanjing", "Chengdu"),
 ("Who were the Terracotta Warriors made to guard?", "Qin Shi Huang, the first emperor, in death", "Genghis Khan", "Mao", "The Ming emperors"),
 ("Who discovered the Terracotta Army in 1974?", "Farmers digging a well", "A British archaeologist", "Soldiers", "A drone survey"),
 ("Most of the Great Wall you see today was built under which dynasty?", "The Ming", "The Qin", "The Han", "The Tang"),
 ("Can you see the Great Wall from space with the naked eye?", "No, it's a myth", "Yes, easily", "Only at night", "Only from the Moon"),
 ("The Beijing palace complex closed to commoners for 500 years?", "The Forbidden City", "The Summer Palace", "Temple of Heaven", "Tiananmen"),
 ("China's Four Great Inventions: paper, printing, the compass and…?", "Gunpowder", "Silk", "Porcelain", "Tea"),
 ("Who founded the People's Republic of China in 1949?", "Mao Zedong", "Sun Yat-sen", "Deng Xiaoping", "Chiang Kai-shek"),
 ("China's best-known beer?", "Tsingtao", "Asahi", "Singha", "Kingfisher"),
 ("The ancient trade network linking China to the Mediterranean?", "The Silk Road", "The Spice Route", "The Amber Road", "The Tea Horse Road only"),
 ("The ancient Chinese general who wrote The Art of War?", "Sun Tzu", "Confucius", "Laozi", "Cao Cao"),
])

# ===================== WORLD WARS =====================
add("World Wars", "WWI", [
 ("WWI years?", "1914–1918", "1912–1916", "1914–1920", "1917–1921"),
 ("Whose assassination in Sarajevo triggered WWI?", "Archduke Franz Ferdinand", "Tsar Nicholas II", "Kaiser Wilhelm II", "King George V"),
 ("Who shot Franz Ferdinand?", "Gavrilo Princip", "Lee Harvey Oswald", "Leon Trotsky", "Otto von Bismarck"),
 ("The Central Powers were Germany, Austria-Hungary, Bulgaria and…?", "The Ottoman Empire", "Italy", "Japan", "Russia"),
 ("The main Allies (Entente) at the start of WWI?", "Britain, France and Russia", "Germany, Italy and Japan", "USA, UK and China", "France, Spain and Portugal"),
 ("Which country switched to the Allied side in 1915?", "Italy", "Japan", "Bulgaria", "Romania only"),
 ("When did the USA join WWI?", "1917", "1914", "1916", "1918"),
 ("Which country left WWI after its 1917 revolution?", "Russia", "France", "Italy", "Serbia"),
 ("The 1915 campaign where the ANZACs landed in Turkey?", "Gallipoli", "The Somme", "Verdun", "Passchendaele"),
 ("Anzac Day is on which date?", "25 April", "11 November", "26 January", "6 June"),
 ("When was the WWI armistice signed?", "11am, 11 November 1918", "28 June 1919", "1 January 1918", "8 May 1918"),
 ("The 1919 treaty that punished Germany?", "Treaty of Versailles", "Treaty of Paris", "Treaty of Ghent", "Treaty of Rome"),
 ("Roughly how many British casualties on the first day of the Somme?", "About 57,000", "About 5,000", "About 200,000", "About 1,000"),
 ("The style of fighting that defined the Western Front?", "Trench warfare", "Blitzkrieg", "Guerrilla war", "Naval blockade only"),
])
add("World Wars", "WWII", [
 ("WWII years?", "1939–1945", "1938–1944", "1940–1946", "1941–1945"),
 ("What started WWII in Europe on 1 September 1939?", "Germany invading Poland", "Pearl Harbor", "Germany invading France", "The Anschluss"),
 ("The main Axis powers?", "Germany, Italy and Japan", "Germany, Russia and Japan", "Italy, Spain and Germany", "Germany, Austria and Turkey"),
 ("The 'Big Three' Allied leaders?", "Churchill, Roosevelt and Stalin", "Churchill, Truman and de Gaulle", "Roosevelt, Stalin and Chiang", "Chamberlain, Roosevelt and Stalin"),
 ("The 1939 pact in which Hitler and Stalin agreed not to fight, and split Poland?", "The Molotov–Ribbentrop Pact", "The Munich Agreement", "The Tripartite Pact", "The Yalta Agreement"),
 ("When did the USSR join the Allies' fight?", "1941, after Germany invaded it", "1939", "1943", "1945"),
 ("What brought the USA into WWII?", "Japan's attack on Pearl Harbor, 7 December 1941", "The sinking of the Lusitania", "D-Day", "The Blitz"),
 ("The 1940 air battle over England?", "The Battle of Britain", "The Blitzkrieg", "Operation Sea Lion", "The Battle of the Atlantic"),
 ("The 1940 evacuation of 338,000 Allied troops from France?", "Dunkirk", "D-Day", "Gallipoli", "Arnhem"),
 ("The brutal battle in Russia widely seen as the turning point of the war in Europe?", "Stalingrad", "Kursk", "Moscow", "Leningrad"),
 ("D-Day, the Normandy landings, happened on…?", "6 June 1944", "8 May 1945", "1 September 1939", "7 December 1941"),
 ("D-Day's code name?", "Operation Overlord", "Operation Barbarossa", "Operation Market Garden", "Operation Torch"),
 ("Germany's 1941 invasion of the USSR?", "Operation Barbarossa", "Operation Sea Lion", "Operation Overlord", "Operation Citadel"),
 ("VE Day, victory in Europe?", "8 May 1945", "6 June 1944", "15 August 1945", "11 November 1945"),
 ("Australia's 1942 jungle campaign against Japan in Papua?", "The Kokoda Track", "Guadalcanal", "Tobruk", "Iwo Jima"),
 ("Japan formally surrendered aboard USS Missouri on…?", "2 September 1945", "6 August 1945", "8 May 1945", "15 August 1946"),
 ("Australian troops famously held which Libyan port in 1941, earning the name 'Rats of'…?", "Tobruk", "Benghazi", "El Alamein", "Tripoli"),
 ("Which neutral country stayed out of WWII despite being surrounded by Axis powers?", "Switzerland", "Belgium", "Norway", "Greece"),
])

# ===================== AI & ROBOTICS / TECH =====================
add("AI & Tech", "AI & robotics", [
 ("The 1956 workshop that coined the term 'artificial intelligence'?", "The Dartmouth workshop", "The Turing Conference", "The MIT Summit", "The Bletchley Meeting"),
 ("Who coined 'artificial intelligence'?", "John McCarthy", "Alan Turing", "Elon Musk", "Marvin Minsky alone"),
 ("IBM's chess computer that beat Garry Kasparov in 1997?", "Deep Blue", "Watson", "AlphaZero", "Stockfish"),
 ("DeepMind's AI that beat Go champion Lee Sedol in 2016?", "AlphaGo", "AlphaFold", "Deep Blue", "Gemini"),
 ("The 2017 Google paper that introduced the Transformer?", "'Attention Is All You Need'", "'Deep Learning'", "'The Bitter Lesson'", "'ImageNet Classification'"),
 ("When did ChatGPT launch?", "November 2022", "June 2020", "March 2023", "2018"),
 ("The chips that power most AI training, made famous by Nvidia?", "GPUs", "CPUs only", "FPGAs", "Quantum chips"),
 ("Where does the word 'robot' come from?", "Karel Čapek's 1920 play R.U.R., from Czech for forced labour", "Isaac Asimov", "A Japanese company", "Leonardo da Vinci"),
 ("Who wrote the Three Laws of Robotics?", "Isaac Asimov", "Arthur C. Clarke", "Philip K. Dick", "Alan Turing"),
 ("The three 'godfathers of AI' who shared the 2018 Turing Award?", "Hinton, LeCun and Bengio", "Musk, Altman and Hassabis", "Turing, McCarthy and Minsky", "Page, Brin and Ng"),
 ("Which AI pioneer shared the 2024 Nobel Prize in Physics?", "Geoffrey Hinton", "Sam Altman", "Yann LeCun", "Andrew Ng"),
 ("DeepMind's AI that predicts protein structures, winning a 2024 Chemistry Nobel?", "AlphaFold", "AlphaGo", "AlphaZero", "Gemini"),
 ("DeepMind's co-founder who shared the 2024 Chemistry Nobel?", "Demis Hassabis", "Mustafa Suleyman", "Geoffrey Hinton", "Ilya Sutskever"),
 ("Boston Dynamics' famous humanoid robot?", "Atlas", "Spot", "Optimus", "ASIMO"),
 ("Boston Dynamics' four-legged robot dog?", "Spot", "Atlas", "BigDog only", "Aibo"),
 ("Tesla's humanoid robot?", "Optimus", "Atlas", "Figure", "Digit"),
 ("Honda's pioneering walking humanoid robot from 2000?", "ASIMO", "Pepper", "Atlas", "Aibo"),
 ("What does an LLM like Claude or ChatGPT fundamentally do?", "Predicts the next token of text", "Searches a database of answers", "Runs on fixed hand-written rules", "Copies Wikipedia"),
])
add("AI & Tech", "Elon Musk", [
 ("Where was Elon Musk born?", "Pretoria, South Africa", "Toronto, Canada", "California, USA", "London, UK"),
 ("Which payment company did Musk's X.com merge into?", "PayPal", "Stripe", "Venmo", "Visa"),
 ("When was SpaceX founded?", "2002", "2008", "1999", "2012"),
 ("SpaceX's first rocket to reach orbit, on its 4th try in 2008?", "Falcon 1", "Falcon 9", "Starship", "Dragon"),
 ("When did SpaceX first land an orbital-class booster back on the ground?", "December 2015", "2008", "2020", "2012"),
 ("SpaceX's first crewed flight to the ISS, Demo-2, launched in…?", "May 2020", "2015", "2023", "2011"),
 ("What did SpaceX first do with Starship's booster in October 2024?", "Caught it with the launch tower's 'chopsticks'", "Landed it on Mars", "Flew it to the Moon", "Landed it on a ship"),
 ("SpaceX's satellite internet service?", "Starlink", "Kuiper", "OneWeb", "SkyNet"),
 ("SpaceX's long-term goal?", "Making humans multiplanetary, starting with Mars", "Mining asteroids", "Space hotels", "Moon tourism only"),
 ("Did Musk found Tesla?", "No, he was an early investor and chairman, later named co-founder", "Yes, alone in 2003", "Yes, with Bill Gates", "No, he bought it in 2015"),
 ("Tesla's first car?", "The Roadster (2008)", "Model S", "Model T", "Cybertruck"),
 ("Musk's brain-computer interface company?", "Neuralink", "Kernel", "Synchron", "OpenAI"),
 ("Musk's AI company that makes Grok?", "xAI", "OpenAI", "DeepMind", "Anthropic"),
 ("Which AI lab did Musk co-found in 2015 before leaving its board in 2018?", "OpenAI", "DeepMind", "Anthropic", "xAI"),
 ("What did Musk buy for about $44 billion in 2022 and rename X?", "Twitter", "Reddit", "TikTok", "Snapchat"),
 ("Musk's tunnelling company?", "The Boring Company", "Hyperloop One", "Tunnel X", "Digging Inc"),
])

# ===================== HUBERMAN / HEALTH =====================
add("Health", "Huberman: light & sleep", [
 ("Who is Andrew Huberman?", "A Stanford neuroscientist with the Huberman Lab podcast", "A Harvard cardiologist", "A sports coach", "A Navy SEAL"),
 ("Huberman's number-one daily habit?", "Get outside light in your eyes early in the day", "Cold showers at night", "Fasting for 24 hours", "10,000 steps"),
 ("How long does Huberman suggest for morning light on a clear day?", "About 5–10 minutes", "About 1 hour", "About 30 seconds", "About 3 hours"),
 ("And on an overcast day?", "Longer, about 20–30 minutes", "Skip it", "Same, 5 minutes", "Use a phone screen instead"),
 ("Why does window or sunglasses light work less well?", "Glass and lenses filter much of the light's intensity", "UV is needed for vision", "It's too bright", "They block blue only at night"),
 ("Which eye cells detect morning light to set your body clock?", "Melanopsin ganglion cells in the retina", "Cones in the fovea", "Rods only", "Cells in the cornea"),
 ("Which brain region is the master circadian clock?", "The suprachiasmatic nucleus (SCN)", "The amygdala", "The cerebellum", "The hippocampus"),
 ("What does early light do to cortisol?", "Triggers a healthy morning cortisol peak that wakes you up", "Lowers it to zero", "Raises it at night", "Has no effect"),
 ("Why does that early cortisol pulse help sleep later?", "It starts a timer for melatonin release about 12–16 hours later", "It burns out your energy", "It blocks adenosine", "It cools the body instantly"),
 ("What does Huberman say bright light between about 10pm and 4am does?", "Suppresses melatonin and can disrupt mood and dopamine", "Improves deep sleep", "Raises testosterone", "Nothing"),
 ("Your body's core temperature naturally does what to start sleep?", "Drops", "Rises", "Stays exactly the same", "Spikes then crashes"),
 ("The hormone of darkness that signals sleep?", "Melatonin", "Cortisol", "Adrenaline", "Dopamine"),
])
add("Health", "Huberman: caffeine & chemistry", [
 ("What builds 'sleep pressure' in your brain the longer you're awake?", "Adenosine", "Serotonin", "Insulin", "Oxytocin"),
 ("How does caffeine keep you alert?", "It blocks adenosine receptors", "It adds dopamine directly", "It raises blood sugar", "It switches off melatonin"),
 ("How long after waking does Huberman suggest delaying caffeine?", "About 90–120 minutes", "Drink it in bed", "6 hours", "Never drink it"),
 ("Huberman's reasoning for delaying caffeine?", "To avoid an afternoon crash as adenosine catches up", "Caffeine is toxic in the morning", "It cancels sunlight", "It blocks melatonin"),
 ("Caffeine's half-life is roughly…?", "About 5 hours", "About 30 minutes", "About 24 hours", "About 1 hour"),
 ("Roughly how long before bed does he suggest stopping caffeine?", "8–10 hours", "1 hour", "30 minutes", "It doesn't matter"),
 ("The 'physiological sigh' is…?", "Two inhales through the nose then a long exhale", "Holding your breath for a minute", "Fast mouth breathing", "A yawn"),
 ("What's the physiological sigh for?", "The fastest real-time way to calm down", "Building lung capacity", "Waking up faster", "Burning fat"),
 ("What's NSDR?", "Non-sleep deep rest, like yoga nidra", "A sleep supplement", "A type of nap alarm", "A breathing app"),
 ("Huberman's warning about 'stacking' dopamine?", "Big peaks are followed by a drop below baseline", "Dopamine stacking is always good", "Dopamine never changes", "Stacking increases baseline forever"),
 ("Roughly how much does cold water immersion raise dopamine in the study he cites?", "About 2.5x, lasting hours", "10%", "100x", "Not at all"),
 ("Huberman's suggested weekly cold exposure total?", "About 11 minutes", "About 2 hours", "1 minute", "60 minutes a day"),
 ("His suggested weekly sauna total?", "About 57 minutes", "About 5 minutes", "About 5 hours", "Daily 2 hours"),
 ("The 'Søberg principle' says to end on…?", "Cold, letting your body rewarm itself", "Heat", "A hot shower", "Stretching"),
 ("Focused work blocks Huberman recommends, matching natural cycles?", "About 90 minutes", "About 10 minutes", "About 4 hours", "About 25 minutes only"),
 ("The neurochemical cocktail Huberman links to alertness, released with cold?", "Norepinephrine (noradrenaline)", "Melatonin", "GABA", "Serotonin only"),
])
