from facts4 import F, add

add("Health", "Sleep", [
 ("Roughly how long is one full sleep cycle?", "About 90 minutes", "About 20 minutes", "About 4 hours", "About 8 hours"),
 ("In which sleep stage is most growth hormone released?", "Deep (slow-wave) sleep", "REM sleep", "Light sleep", "While dreaming"),
 ("What does alcohol before bed do to sleep?", "Fragments it and suppresses REM", "Deepens REM", "Improves recovery", "Nothing measurable"),
 ("Huberman's well-known sleep supplement 'stack'?", "Magnesium threonate, apigenin and theanine", "Melatonin, caffeine and zinc", "Ashwagandha, iron and fish oil", "Creatine, vitamin C and CBD"),
 ("Huberman's stance on regular melatonin supplements?", "Cautious, he doesn't recommend them for routine use", "Take 10 mg nightly", "Best sleep aid there is", "Only with coffee"),
 ("Bedroom temperature for good sleep should be…?", "Cool", "Warm", "Hot", "It doesn't matter"),
 ("What does Huberman say viewing the evening sun near sunset helps with?", "Buffering the effects of artificial light later at night", "Raising cortisol before bed", "Skipping morning light", "Burning fat"),
 ("Which sleep habit does Huberman call most important for a stable body clock?", "A consistent wake-up time", "Sleeping in on weekends", "Napping every afternoon", "Going to bed at 8pm"),
 ("The brain's waste-clearing system that ramps up during deep sleep?", "The glymphatic system", "The lymph nodes", "The vagus nerve", "The pineal gland"),
 ("Short sleep raises which hunger hormone?", "Ghrelin", "Leptin", "Insulin", "Melatonin"),
 ("How much sleep do most adults need?", "7–9 hours", "4–5 hours", "10–12 hours", "Exactly 6 hours"),
 ("Why does Huberman suggest using low lamps instead of overhead lights at night?", "Light-sensitive retina cells mostly look up, so overhead light hits them hardest", "Lamps use less power", "Overhead lights are blue", "It's easier to read"),
 ("Roughly how bright is a sunny day compared with indoor lighting?", "About 100,000 lux vs about 500 lux", "About the same", "About 2x brighter", "About 1,000 lux vs 900 lux"),
 ("The gland that releases melatonin?", "The pineal gland", "The pituitary gland", "The adrenal gland", "The thyroid"),
 ("Cortisol naturally peaks about how long after waking?", "30–45 minutes", "6 hours", "Right before bed", "At midnight"),
 ("One week of 5-hour nights lowered young men's testosterone by about…?", "10–15%", "1%", "50%", "90%"),
])
add("Health", "Stress & breathing", [
 ("Box breathing uses which pattern?", "Inhale, hold, exhale, hold, all equal counts", "Two inhales, long exhale", "Fast mouth breathing", "Hold breath for 2 minutes"),
 ("Which elite military unit popularised box breathing?", "US Navy SEALs", "French Foreign Legion", "Gurkhas", "Roman legions"),
 ("In the 2023 Stanford study Huberman co-led, 5 minutes a day of what improved mood most?", "Cyclic sighing (long exhales)", "Mindfulness meditation", "Box breathing", "Breath holds"),
 ("Cyclic hyperventilation, Wim Hof style, mainly does what?", "Raises adrenaline and alertness", "Puts you to sleep", "Lowers heart rate instantly", "Lowers body temperature"),
 ("Which visual trick does Huberman say calms the stress response?", "Widening your gaze into panoramic vision", "Staring at a phone", "Closing one eye", "Crossing your eyes"),
 ("Stanford's Alia Crum found that viewing stress as what improves outcomes?", "Enhancing rather than debilitating", "Something to always avoid", "Purely genetic", "A sign of weakness"),
 ("Is short-term (acute) stress always harmful?", "No, it can sharpen focus and immunity; chronic stress is the problem", "Yes, always", "Only in the morning", "Only for athletes"),
 ("Breathing through which does Huberman favour for most exercise and sleep?", "The nose", "The mouth", "Alternating", "Doesn't matter"),
 ("Higher heart rate variability (HRV) generally signals…?", "Better recovery and resilience", "Illness", "Dehydration", "Overtraining"),
])
add("Health", "Focus, learning & mind", [
 ("Where does Huberman say most of the actual rewiring from learning happens?", "During sleep and deep rest afterwards", "During the learning itself", "Only in childhood", "During exercise"),
 ("What does Huberman say short pauses of about 10 seconds during learning allow?", "The brain to replay what was just learned, much faster", "Muscle recovery", "Cortisol to drop to zero", "Nothing useful"),
 ("Huberman's quick tool to boost focus before work?", "Fixing your eyes on one point for 30–60 seconds", "Closing your eyes for 10 minutes", "Drinking ice water", "Listening to loud music"),
 ("The study Huberman cites found how much daily meditation improved attention and memory after 8 weeks?", "13 minutes", "2 hours", "1 minute", "45 minutes"),
 ("What does Huberman say NSDR straight after learning can help with?", "Retaining what you learned", "Forgetting it faster", "Raising cortisol", "Building muscle"),
 ("Dopamine is mainly the molecule of…?", "Motivation and pursuit, more than pleasure itself", "Sleep", "Pain", "Digestion only"),
 ("To keep motivation high, Huberman suggests rewarding yourself…?", "Intermittently and unpredictably", "Every single time", "Never", "Only on Sundays"),
 ("Huberman's growth-mindset tip for hard tasks?", "Learn to attach the reward to the effort itself", "Only celebrate results", "Avoid hard tasks", "Use caffeine every hour"),
 ("Roughly what share of the body's serotonin is made in the gut?", "About 90%", "About 5%", "About 50%", "None"),
 ("The 'bonding' hormone released by touch and closeness?", "Oxytocin", "Adrenaline", "Cortisol", "Insulin"),
 ("The 80-plus-year Harvard study found the strongest predictor of a happy, healthy life was…?", "Close relationships", "Income", "IQ", "Genetics"),
 ("Which gratitude practice does Huberman say works most powerfully?", "Receiving thanks or watching stories of people being helped", "Writing a quick list of things", "Saying thanks to yourself", "Thinking about money"),
 ("The 'runner's high' is now strongly linked to…?", "Endocannabinoids", "Caffeine", "Melatonin", "Insulin"),
])
add("Health", "Gym & training", [
 ("Zone 2 cardio is a pace where you can…?", "Still hold a conversation", "Barely breathe", "Only sprint", "Sing loudly"),
 ("Roughly how much Zone 2 per week does Huberman suggest?", "About 150–200 minutes", "About 10 minutes", "About 15 hours", "None"),
 ("What does VO2 max measure?", "The most oxygen your body can use during exercise", "Lung size", "Max heart rate", "Muscle strength"),
 ("Why do longevity experts like Peter Attia focus on VO2 max?", "It's one of the strongest predictors of lifespan", "It's easy to fake", "It measures body fat", "It only matters for athletes"),
 ("The Norwegian 4x4 protocol for VO2 max is…?", "4 minutes hard, 3 minutes easy, 4 times", "4 reps, 4 sets", "4 km at max pace", "4 hours of Zone 2"),
 ("Rep range typically used for building maximum strength?", "About 3–5 reps", "About 30–50 reps", "1 rep only, every set", "100 reps"),
 ("What actually drives muscle growth across a wide rep range (roughly 5–30)?", "Taking sets close to failure", "Always lifting light", "Training only once a month", "Only using machines"),
 ("Roughly how many hard sets per muscle per week for growth?", "About 10 or more", "1", "50", "100"),
 ("Recommended rest between heavy strength sets?", "About 3–5 minutes", "10 seconds", "15 minutes", "No rest"),
 ("The principle of gradually increasing load, reps or difficulty?", "Progressive overload", "Periodic underload", "Muscle confusion", "Deloading"),
 ("When do muscles actually grow?", "During recovery after training", "During the set", "While warming up", "Only while sleeping in the gym"),
 ("What's DOMS?", "Delayed-onset muscle soreness", "A type of protein", "A heart condition", "A stretching method"),
 ("The 'eccentric' phase of a lift is when the muscle…?", "Lengthens under load, like lowering the bar", "Shortens", "Stays still", "Rests completely"),
 ("Which is a compound lift?", "Squat", "Bicep curl", "Leg extension", "Calf raise"),
 ("Grip strength is linked in research to…?", "Lower all-cause mortality", "Higher injury risk", "Poor sleep", "Nothing"),
 ("Huberman suggests keeping workouts to roughly how long after warm-up?", "About an hour", "About 3 hours", "About 5 minutes", "There's no limit"),
 ("In Huberman's weekly fitness protocol, Sunday is usually…?", "A long, steady endurance session", "Heavy legs", "Rest only", "Max sprints"),
 ("Who's the exercise scientist Huberman often brings on for training advice?", "Andy Galpin", "Matthew Walker", "David Goggins", "Joe Rogan"),
 ("Huberman says avoid cold plunges for several hours after hypertrophy training because…?", "Cold may blunt muscle growth adaptations", "It causes cramps", "It raises cortisol forever", "It wastes protein"),
 ("Is lactate just a waste product that causes soreness?", "No, it's also a fuel your body uses", "Yes, purely waste", "It causes DOMS", "It's a type of fat"),
 ("Zone 2 training especially builds more…?", "Mitochondria", "Bone density only", "Fast-twitch fibres", "Testosterone"),
 ("Peter Attia's book about living longer and better?", "Outlive", "Why We Sleep", "Atomic Habits", "Can't Hurt Me"),
 ("Peter Attia's idea of training now for the 10 physical tasks you want to do in your final decade?", "The Centenarian Decathlon", "The Zone 2 Rule", "The 4x4", "Project 100"),
 ("The calories you burn through non-exercise movement like walking and fidgeting?", "NEAT", "BMR", "EPOC", "VO2"),
])
add("Health", "Nutrition, hydration & supplements", [
 ("Basic recommended daily protein for the average adult?", "About 0.8 g per kg of bodyweight", "About 5 g per kg", "About 0.1 g per kg", "About 50 g per meal"),
 ("A common protein target Huberman and Galpin give for people training hard?", "About 1 g per pound of bodyweight", "About 10 g a day", "Double the bodyweight in grams per meal", "None needed"),
 ("Which amino acid is key for switching on muscle protein synthesis?", "Leucine", "Glycine", "Taurine", "Glutamine"),
 ("Typical daily dose of creatine monohydrate?", "About 5 g", "About 50 g", "About 0.1 g", "About 500 g"),
 ("Besides muscle, creatine is being studied for benefits to…?", "The brain and cognition", "Eyesight", "Hair growth", "Hearing"),
 ("The 'Galpin equation' for drinking during exercise?", "Bodyweight in pounds ÷ 30 = ounces every 15 minutes", "1 litre per hour, always", "Drink only when thirsty", "Half your weight in litres"),
 ("The three main electrolytes Huberman talks about?", "Sodium, potassium and magnesium", "Iron, zinc and copper", "Calcium, iodine and selenium", "Sugar, salt and caffeine"),
 ("Caffeine dose shown to boost exercise performance?", "About 1–3 mg per kg of bodyweight (higher doses also studied)", "About 50 mg per kg", "One coffee bean", "None"),
 ("In the Stanford fermented-food study, eating more fermented food led to…?", "More gut microbe diversity and less inflammation", "Weight gain", "Worse sleep", "No change"),
 ("Roughly how many servings of fermented food a day does Huberman suggest?", "About 2–4", "About 20", "One a week", "None"),
 ("Which omega-3 does Huberman highlight for mood, at about 1 g or more a day?", "EPA", "ALA", "Omega-6", "Omega-9"),
 ("Vitamin D is mainly made by the body from…?", "Sunlight on the skin", "Drinking water", "Sleep", "Coffee"),
 ("The Salk researcher behind time-restricted eating that Huberman often features?", "Satchin Panda", "Matthew Walker", "Peter Attia", "Andrew Galpin"),
 ("A short walk after a meal does what to blood sugar?", "Blunts the spike", "Doubles it", "Nothing", "Makes it drop dangerously"),
 ("What toxic compound does the body first turn alcohol into?", "Acetaldehyde", "Glucose", "Lactate", "Ketones"),
 ("Huberman's conclusion after his alcohol episode?", "No amount of alcohol is good for health", "Red wine daily is healthy", "Beer is fine, spirits aren't", "It improves sleep"),
 ("The hormone that tells you you're full?", "Leptin", "Ghrelin", "Cortisol", "Adrenaline"),
 ("The hormone that moves glucose from the blood into cells?", "Insulin", "Glucagon", "Melatonin", "Dopamine"),
 ("Even 1–2% dehydration can measurably hurt…?", "Focus and physical performance", "Eyesight permanently", "Height", "Nothing"),
])
add("Health", "Heat & cold", [
 ("Finnish studies link sauna use 4–7 times a week to…?", "Lower risk of cardiovascular death", "Higher heart risk", "Weight gain", "No difference"),
 ("Regular cold exposure increases which calorie-burning tissue?", "Brown fat", "White belly fat", "Muscle fibre count", "Bone marrow"),
 ("Why does Huberman say to let yourself shiver in cold exposure?", "Shivering releases a molecule that activates brown fat", "It warms the water", "It builds muscle", "It lowers dopamine"),
 ("How cold should cold exposure be, per Huberman?", "Uncomfortably cold but safe to stay in", "As close to freezing as possible", "Room temperature", "Lukewarm"),
 ("Huberman's podcast first launched in…?", "2021", "2015", "2010", "2024"),
 ("Who's the sleep scientist and author of 'Why We Sleep'?", "Matthew Walker", "Andrew Huberman", "Peter Attia", "Rhonda Patrick"),
])
