from facts2 import F, add

# ===================== ASIA =====================
add("Vietnam", "Vietnam", [
 ("Capital of Vietnam?", "Hanoi", "Ho Chi Minh City", "Da Nang", "Hue"),
 ("Vietnam's largest city?", "Ho Chi Minh City", "Hanoi", "Hai Phong", "Da Nang"),
 ("Ho Chi Minh City's old name?", "Saigon", "Hue", "Tonkin", "Annam"),
 ("Vietnam's currency?", "Dong", "Baht", "Kip", "Riel"),
 ("Vietnam's popular beers?", "Bia Hà Nội, Saigon, 333 and Larue", "Chang and Singha", "Beerlao", "Bintang"),
 ("Hanoi's cheap, fresh, unpasteurised street beer?", "Bia hơi", "Bia 333", "Rượu", "Chang"),
 ("Hanoi's famous whipped-yolk drink?", "Egg coffee (cà phê trứng)", "Bubble tea", "Lotus tea", "Coconut coffee"),
 ("Vietnam's noodle soup, usually beef or chicken?", "Phở", "Bún chả", "Bánh mì", "Cao lầu"),
 ("Hanoi's grilled pork with noodles dish, eaten by Obama with Anthony Bourdain?", "Bún chả", "Phở", "Bánh xèo", "Cơm tấm"),
 ("Vietnam's limestone-island bay, a UNESCO site?", "Ha Long Bay", "Nha Trang Bay", "Phu Quoc", "Lan Ha only"),
 ("The lantern-lit ancient trading town in central Vietnam?", "Hoi An", "Hue", "Sapa", "Dalat"),
 ("The underground network used by Viet Cong fighters near Saigon?", "Cu Chi Tunnels", "Vinh Moc", "Ho Chi Minh Trail", "Dien Bien Phu"),
 ("The Vietnam War ended with the fall of Saigon in…?", "1975", "1968", "1973", "1954"),
 ("Vietnam's 1954 victory that ended French colonial rule?", "Dien Bien Phu", "Tet Offensive", "Khe Sanh", "Hue"),
 ("Vietnamese is unusual in Asia for using…?", "A Latin alphabet with accents", "Chinese characters only", "A Sanskrit script", "Arabic script"),
 ("The famous motorbike loop in Vietnam's far north?", "The Ha Giang Loop", "The Hai Van Pass", "The Mae Hong Son Loop", "The Thakhek Loop"),
])
add("Thailand", "Thailand", [
 ("Capital of Thailand?", "Bangkok", "Chiang Mai", "Phuket", "Pattaya"),
 ("Thailand's currency?", "Baht", "Dong", "Ringgit", "Kip"),
 ("Thailand's best-known beers?", "Chang, Singha and Leo", "Tiger and Anchor", "Beerlao", "San Miguel"),
 ("What's unique about Thailand's history in Southeast Asia?", "It was never colonised by a European power", "It was a French colony", "It was a British colony", "It was Dutch"),
 ("Thailand's April new-year water fight festival?", "Songkran", "Loy Krathong", "Yi Peng", "Tet"),
 ("The festival of floating lanterns and baskets in November?", "Loy Krathong", "Songkran", "Diwali", "Vesak"),
 ("Thailand's national sport, 'the art of eight limbs'?", "Muay Thai", "Sepak takraw", "Krabi-krabong", "Kickboxing"),
 ("Thailand's spicy, sour prawn soup?", "Tom yum", "Tom kha", "Pad see ew", "Massaman"),
 ("Bangkok's full ceremonial name holds what record?", "World's longest place name", "Oldest city name", "Shortest capital name", "Most spellings"),
 ("Thailand's northern 'rose of the north' city?", "Chiang Mai", "Chiang Rai", "Pai", "Sukhothai"),
 ("Thailand's current king, crowned 2019?", "Rama X (Vajiralongkorn)", "Rama IX (Bhumibol)", "Rama V", "Prajadhipok"),
 ("Thailand was called what until 1939?", "Siam", "Burma", "Ayutthaya", "Lanna"),
])
add("Indonesia", "Bali & Indonesia", [
 ("Bali belongs to which country?", "Indonesia", "Malaysia", "Thailand", "Philippines"),
 ("Indonesia's capital?", "Jakarta (with Nusantara being built as a new capital)", "Denpasar", "Surabaya", "Bandung"),
 ("Bali's main religion, unusual in Indonesia?", "Hinduism", "Islam", "Buddhism", "Christianity"),
 ("Indonesia's most common beer?", "Bintang", "Tiger", "Singha", "Anker only"),
 ("Indonesia's currency?", "Rupiah", "Ringgit", "Rupee", "Baht"),
 ("Bali's 'Day of Silence', when the whole island shuts down?", "Nyepi", "Galungan", "Kuningan", "Ramadan"),
 ("Bali's famous sunrise volcano trek?", "Mount Batur", "Mount Agung", "Mount Bromo", "Mount Rinjani"),
 ("Bali's highest and most sacred volcano?", "Mount Agung", "Mount Batur", "Mount Merapi", "Mount Kerinci"),
 ("Bali's spit-roasted suckling pig?", "Babi guling", "Nasi goreng", "Rendang", "Satay lilit"),
 ("Bali's arts-and-rice-terraces town?", "Ubud", "Kuta", "Seminyak", "Canggu"),
 ("Bali's clifftop temple and surf spot in the south?", "Uluwatu", "Tanah Lot", "Besakih", "Lempuyang"),
 ("Roughly how many islands make up Indonesia?", "About 17,000", "About 200", "About 2,000", "About 50,000"),
 ("The world's largest Muslim-majority country by population?", "Indonesia", "Pakistan", "Egypt", "Saudi Arabia"),
])
add("Laos", "Laos", [
 ("Capital of Laos?", "Vientiane", "Luang Prabang", "Pakse", "Vang Vieng"),
 ("Laos's dominant beer?", "Beerlao", "Chang", "Saigon", "Angkor"),
 ("Laos's currency?", "Kip", "Dong", "Baht", "Riel"),
 ("Laos's grim world record from the Vietnam War era?", "Most heavily bombed country per capita in history", "Most landmines in Africa", "Largest refugee exodus", "Longest war"),
 ("Roughly how many cluster bomblets were dropped on Laos?", "About 270 million", "About 10,000", "About 2 million", "About 1 billion"),
 ("Laos's UNESCO town famous for the dawn monks' alms-giving?", "Luang Prabang", "Vientiane", "Vang Vieng", "Pakse"),
 ("The turquoise multi-tiered waterfalls near Luang Prabang?", "Kuang Si", "Tad Sae", "Khone Phapheng", "Erawan"),
 ("Laos's staple, eaten by hand in balls?", "Sticky rice", "Jasmine rice", "Noodles", "Flatbread"),
 ("Laos's minced meat and herb 'salad', a national dish?", "Larb", "Som tam", "Khao soi", "Mok pa"),
 ("Is Laos landlocked?", "Yes, the only landlocked country in Southeast Asia", "No, it has a short coast", "No, it's an island", "Only in summer"),
 ("Laos's famous river-tubing backpacker town?", "Vang Vieng", "Pakse", "Nong Khiaw", "Thakhek"),
])
add("Sri Lanka", "Sri Lanka", [
 ("Sri Lanka's official legislative capital?", "Sri Jayawardenepura Kotte", "Colombo", "Kandy", "Galle"),
 ("Sri Lanka's biggest city and commercial capital?", "Colombo", "Kandy", "Jaffna", "Galle"),
 ("Sri Lanka's two main languages?", "Sinhala and Tamil", "Hindi and Tamil", "Sinhala and English only", "Bengali and Tamil"),
 ("Sri Lanka's old name until 1972?", "Ceylon", "Serendib only", "Lanka", "Taprobane"),
 ("Sri Lanka's best-known beer?", "Lion", "Kingfisher", "Three Coins only", "Tiger"),
 ("The giant rock fortress with ancient frescoes?", "Sigiriya", "Dambulla", "Adam's Peak", "Anuradhapura"),
 ("Kandy's temple holds which relic?", "A tooth of the Buddha", "The Buddha's footprint", "A hair of the Buddha", "The Buddha's bowl"),
 ("The famous railway viaduct near Ella?", "Nine Arch Bridge", "Golden Gate", "Pamban Bridge", "Hill Country Arch"),
 ("Sri Lanka's world-famous export crop?", "Tea", "Coffee", "Rubber only", "Cocoa"),
 ("Sri Lanka gave the world its first…?", "Female prime minister, Sirimavo Bandaranaike, 1960", "Female president", "Buddhist monarchy", "Tea plantation"),
 ("Sri Lanka's currency?", "Sri Lankan rupee", "Taka", "Rupiah", "Dinar"),
])

# ===================== EUROPE =====================
add("England", "England", [
 ("Capital of England and the UK?", "London", "Manchester", "Birmingham", "Edinburgh"),
 ("The UK's best-selling lager?", "Carling", "Stella Artois", "Fosters", "Heineken"),
 ("The 1215 charter that limited the English king's power?", "Magna Carta", "The Bill of Rights", "Domesday Book", "The Petition of Right"),
 ("'Big Ben' is actually the name of…?", "The great bell", "The tower", "The clock face", "The whole Parliament"),
 ("The 1066 invasion that changed English history?", "The Norman Conquest", "The Viking raids", "The Roman invasion", "The Spanish Armada"),
 ("Who won the Battle of Hastings in 1066?", "William the Conqueror", "King Harold", "Alfred the Great", "Richard the Lionheart"),
 ("The prehistoric stone circle on Salisbury Plain?", "Stonehenge", "Avebury", "Skara Brae", "Callanish"),
 ("Henry VIII broke from the Pope mainly to…?", "Divorce Catherine of Aragon", "Avoid taxes", "Invade France", "Marry a Spanish princess"),
 ("Britain's longest-reigning monarch?", "Elizabeth II", "Victoria", "George III", "Henry VIII"),
 ("Current UK monarch?", "Charles III", "William V", "Elizabeth II", "George VII"),
 ("The UK's currency?", "Pound sterling", "Euro", "Shilling", "Crown"),
])
add("Norway", "Norway", [
 ("Capital of Norway?", "Oslo", "Bergen", "Trondheim", "Stavanger"),
 ("Norway's currency?", "Norwegian krone", "Euro", "Krona", "Mark"),
 ("Norway's popular beers?", "Ringnes, Hansa and Aass", "Carlsberg and Tuborg", "Norrlands Guld", "Lapin Kulta"),
 ("Is Norway in the EU?", "No, it voted no twice", "Yes, since 1995", "Yes, a founding member", "Only for fishing"),
 ("Norway's oil fund holds what title?", "World's largest sovereign wealth fund", "Smallest in Europe", "Oldest bank", "Largest gold reserve"),
 ("The Norwegian who first reached the South Pole in 1911?", "Roald Amundsen", "Fridtjof Nansen", "Robert Scott", "Thor Heyerdahl"),
 ("Which Nobel Prize is awarded in Oslo?", "The Peace Prize", "Literature", "Physics", "All of them"),
 ("Norway's flat-topped cliff over Lysefjord?", "Preikestolen (Pulpit Rock)", "Trolltunga", "Kjeragbolten", "Nordkapp"),
 ("Norway's sweet, caramel-coloured cheese?", "Brunost (brown cheese)", "Jarlsberg only", "Gamalost", "Gouda"),
 ("The UNESCO fjord famous for the Seven Sisters waterfall?", "Geirangerfjord", "Sognefjord", "Oslofjord", "Lysefjord"),
 ("Norway's famous seafaring raiders of 793–1066?", "The Vikings", "The Normans", "The Saxons", "The Goths"),
])
add("Denmark", "Denmark", [
 ("Capital of Denmark?", "Copenhagen", "Aarhus", "Odense", "Aalborg"),
 ("Denmark's currency?", "Danish krone", "Euro", "Krona", "Mark"),
 ("Denmark's famous beer brands?", "Carlsberg and Tuborg", "Heineken and Amstel", "Ringnes", "Beck's"),
 ("LEGO's name comes from Danish 'leg godt', meaning…?", "Play well", "Build big", "Little bricks", "Lucky toy"),
 ("The Danish idea of cosy contentment?", "Hygge", "Lagom", "Fika", "Sisu"),
 ("Copenhagen's 1843 amusement park that inspired Walt Disney?", "Tivoli Gardens", "Legoland", "Bakken", "Liseberg"),
 ("Copenhagen's statue based on a Hans Christian Andersen tale?", "The Little Mermaid", "The Ugly Duckling", "The Snow Queen", "Thumbelina"),
 ("Denmark's open sandwich?", "Smørrebrød", "Smörgåsbord", "Pølse", "Frikadeller"),
 ("Denmark's flag, the Dannebrog, is known as…?", "The oldest continuously used national flag", "The newest flag", "The only round flag", "A copy of Sweden's"),
 ("Copenhagen's colourful canal-side harbour?", "Nyhavn", "Christiania", "Strøget", "Islands Brygge"),
])
add("Sweden", "Sweden", [
 ("Capital of Sweden?", "Stockholm", "Gothenburg", "Malmö", "Uppsala"),
 ("Sweden's currency?", "Swedish krona", "Euro", "Krone", "Mark"),
 ("Sweden's popular beers?", "Norrlands Guld and Pripps Blå", "Carlsberg", "Lapin Kulta", "Ringnes"),
 ("The Swedish coffee-and-cake break?", "Fika", "Hygge", "Lagom", "Smörgås"),
 ("Sweden's state-run liquor store monopoly?", "Systembolaget", "Vinmonopolet", "Alko", "Bolaget Norge"),
 ("The warship that sank on its maiden voyage in 1628, now a museum?", "The Vasa", "The Mary Rose", "The Wasa II", "The Kronan"),
 ("Stockholm is spread across how many islands?", "14", "3", "100", "1"),
 ("Famous Swedish companies?", "IKEA, Volvo, Spotify, H&M", "LEGO and Carlsberg", "Nokia and Kone", "Equinor and DNB"),
 ("The Swedish pop band that won Eurovision in 1974 with 'Waterloo'?", "ABBA", "Roxette", "Ace of Base", "Europe"),
 ("The Swede whose will created the Nobel Prizes?", "Alfred Nobel, inventor of dynamite", "Carl Linnaeus", "Anders Celsius", "Ingvar Kamprad"),
])
add("Germany", "Germany", [
 ("Capital of Germany?", "Berlin", "Munich", "Bonn", "Frankfurt"),
 ("Germany's best-selling beers include…?", "Krombacher, Beck's and Paulaner", "Carlsberg and Tuborg", "Peroni and Moretti", "Stella and Leffe"),
 ("The 1516 Bavarian beer purity law?", "The Reinheitsgebot", "The Bierordnung", "The Brauerei Act", "The Oktobergesetz"),
 ("Under the purity law beer could contain only water, barley and…?", "Hops (yeast was added later)", "Wheat", "Sugar", "Honey"),
 ("Munich's beer festival actually starts in which month?", "September", "October 31", "August", "November"),
 ("Berlin's signature street snack?", "Currywurst", "Bratwurst", "Schnitzel", "Pretzel"),
 ("The neoclassical gate that became a symbol of division and reunification?", "The Brandenburg Gate", "The Victory Column", "Checkpoint Charlie", "The Reichstag"),
 ("Germany's parliament building with a glass dome?", "The Reichstag", "The Bundesrat", "The Rotes Rathaus", "Bellevue Palace"),
])
add("Germany", "Berlin Wall", [
 ("When did the Berlin Wall go up?", "13 August 1961", "1945", "1949", "1953"),
 ("When did the Berlin Wall fall?", "9 November 1989", "3 October 1990", "1991", "25 December 1989"),
 ("When was Germany officially reunified?", "3 October 1990", "9 November 1989", "1 January 1991", "1985"),
 ("Who built the Berlin Wall?", "Communist East Germany (GDR)", "The Allies", "West Germany", "The USSR directly"),
 ("The GDR's official name for the Wall?", "Anti-Fascist Protection Rampart", "Iron Curtain", "Peace Wall", "Freedom Barrier"),
 ("The real reason the Wall was built?", "To stop East Germans fleeing to the West", "To keep out Western armies", "To mark a river", "To protect from bombing"),
 ("Roughly how many people were killed at the Wall?", "At least 140", "About 5", "About 10,000", "None"),
 ("The 'death strip' was…?", "The guarded no-man's land between the inner and outer walls", "A street in Kreuzberg", "A minefield in Bavaria", "A river crossing"),
 ("The famous Allied crossing point between East and West Berlin?", "Checkpoint Charlie", "Checkpoint Alpha", "Brandenburg Gate", "Potsdamer Platz"),
 ("The longest surviving stretch of the Wall, covered in murals?", "East Side Gallery", "Bernauer Strasse", "Topography of Terror", "Mauerpark"),
 ("JFK's famous 1963 Berlin line?", "'Ich bin ein Berliner'", "'Tear down this wall'", "'The wall must fall'", "'Freedom for Berlin'"),
 ("Who said 'Mr. Gorbachev, tear down this wall!' in 1987?", "Ronald Reagan", "John F. Kennedy", "Margaret Thatcher", "Helmut Kohl"),
 ("What triggered the Wall opening on 9 November 1989?", "A botched announcement that borders were open 'immediately'", "A US airstrike", "A treaty signed that day", "Gorbachev visiting"),
 ("After WWII, Berlin was split into how many occupation sectors?", "Four", "Two", "Three", "Six"),
 ("The 1948–49 operation that flew supplies into blockaded West Berlin?", "The Berlin Airlift", "Operation Overlord", "The Marshall Plan", "Operation Paperclip"),
])
add("Germany", "Hitler & the Nazis", [
 ("Where was Adolf Hitler born?", "Austria", "Bavaria", "Berlin", "Czechoslovakia"),
 ("When did Hitler become Chancellor of Germany?", "January 1933", "1923", "1939", "1929"),
 ("Hitler's failed 1923 coup attempt in Munich?", "The Beer Hall Putsch", "The Reichstag Fire", "The Night of the Long Knives", "Kristallnacht"),
 ("The book Hitler wrote in prison?", "Mein Kampf", "Das Kapital", "The Prince", "Der Untergang"),
 ("The 1938 night of violent attacks on Jewish homes and synagogues?", "Kristallnacht", "The Night of the Long Knives", "The Wannsee Conference", "The Anschluss"),
 ("Roughly how many Jews were murdered in the Holocaust?", "About 6 million", "About 600,000", "About 20 million", "About 1 million"),
 ("The largest Nazi death camp?", "Auschwitz-Birkenau", "Dachau", "Bergen-Belsen", "Buchenwald"),
 ("How and where did Hitler die?", "Suicide in his Berlin bunker, 30 April 1945", "Executed at Nuremberg", "Killed in a bombing raid", "Escaped to Argentina"),
 ("The post-war trials of leading Nazis were held in…?", "Nuremberg", "Berlin", "The Hague", "Munich"),
])
add("Spain", "Spain", [
 ("Capital of Spain?", "Madrid", "Barcelona", "Seville", "Valencia"),
 ("Spain's popular beers?", "Mahou, Estrella Damm, Estrella Galicia and Cruzcampo", "Super Bock and Sagres", "Peroni", "Quilmes"),
 ("Paella originally comes from which region?", "Valencia", "Andalusia", "Catalonia", "Galicia"),
 ("Gaudí's unfinished basilica, begun in 1882?", "Sagrada Família", "Casa Batlló", "Park Güell", "La Pedrera"),
 ("Granada's Moorish palace-fortress?", "The Alhambra", "The Alcázar", "The Mezquita", "El Escorial"),
 ("The dictator who ruled Spain from 1939 to 1975?", "Francisco Franco", "Primo de Rivera", "Salazar", "Mussolini"),
 ("The tomato-throwing festival in Buñol?", "La Tomatina", "San Fermín", "Las Fallas", "Feria de Abril"),
 ("Pamplona's running of the bulls festival?", "San Fermín", "La Tomatina", "Semana Santa", "La Mercè"),
 ("Besides Spanish, which language is spoken around Barcelona?", "Catalan", "Basque", "Galician", "Portuguese"),
 ("The 1492 voyage sponsored by Spain's monarchs?", "Columbus's first voyage to the Americas", "Magellan's circumnavigation", "Cortés to Mexico", "Vasco da Gama to India"),
 ("Spain's cured ham from acorn-fed black pigs?", "Jamón ibérico", "Jamón serrano", "Prosciutto", "Chorizo"),
])
add("Portugal", "Portugal", [
 ("Capital of Portugal?", "Lisbon", "Porto", "Coimbra", "Faro"),
 ("Portugal's two big beers?", "Super Bock and Sagres", "Mahou and Damm", "Peroni and Moretti", "Cristal and Escudo"),
 ("Portugal's famous custard tart?", "Pastel de nata", "Bola de Berlim", "Queijada", "Bolo rei"),
 ("Portugal's melancholy folk music?", "Fado", "Flamenco", "Tango", "Morna"),
 ("The Portuguese explorer who reached India by sea in 1498?", "Vasco da Gama", "Magellan", "Bartolomeu Dias", "Henry the Navigator"),
 ("The disaster that flattened Lisbon in 1755?", "An earthquake, tsunami and fire", "A plague", "A volcano", "A Spanish invasion"),
 ("Portugal's alliance with England, the world's oldest still in force, dates from…?", "1386, the Treaty of Windsor", "1815", "1704", "1940"),
 ("The 1974 bloodless coup that ended Portugal's dictatorship?", "The Carnation Revolution", "The Velvet Revolution", "The Rose Revolution", "The Orange Revolution"),
 ("The fortified wine from the Douro Valley?", "Port", "Madeira", "Sherry", "Vinho verde"),
])
add("Albania", "Albania", [
 ("Capital of Albania?", "Tirana", "Durrës", "Shkodër", "Vlorë"),
 ("Albania's currency?", "Lek", "Euro", "Dinar", "Kuna"),
 ("Albania's popular beers?", "Birra Tirana and Korça", "Nikšićko", "Ožujsko", "Mythos"),
 ("Albania's communist dictator from 1944 to 1985?", "Enver Hoxha", "Josip Tito", "Nicolae Ceaușescu", "Todor Zhivkov"),
 ("What was banned for ordinary Albanians under communism?", "Owning a private car", "Owning a radio", "Going to school", "Eating meat"),
 ("Private car ownership became legal in Albania around…?", "1991", "1960", "2010", "1975"),
 ("Roughly how many bunkers did Hoxha build?", "About 173,000", "About 1,700", "About 17,000", "About 2 million"),
 ("Why did Hoxha build so many bunkers?", "Paranoia about invasion, with every citizen trained to fight", "Nuclear tests", "Tourism", "Storing grain"),
 ("Which famous nun was ethnically Albanian?", "Mother Teresa", "Hildegard of Bingen", "Saint Clare", "Sister Lucia"),
 ("Albania's national hero who fought the Ottomans?", "Skanderbeg", "Ali Pasha", "Ismail Qemali", "Enver Hoxha"),
 ("What's on Albania's red flag?", "A black double-headed eagle", "A gold lion", "A white cross", "A red star"),
 ("Albania's turquoise beach village on the Riviera?", "Ksamil", "Budva", "Hvar", "Sarandë only"),
 ("Albania's ancient Greek and Roman ruins near Ksamil?", "Butrint", "Apollonia only", "Delphi", "Salona"),
 ("A common Albanian head gesture surprise?", "Nodding can mean no and shaking can mean yes", "Bowing means no", "Winking means yes", "Thumbs up is rude"),
 ("Albania's flaky pastry snack?", "Byrek", "Baklava", "Ćevapi", "Gibanica"),
])
add("Montenegro", "Montenegro", [
 ("Capital of Montenegro?", "Podgorica", "Cetinje", "Kotor", "Budva"),
 ("Montenegro's old royal capital?", "Cetinje", "Kotor", "Bar", "Herceg Novi"),
 ("What currency does Montenegro use, despite not being in the EU?", "The euro", "Dinar", "Lek", "Kuna"),
 ("What does 'Montenegro' mean?", "Black Mountain", "Green Valley", "Blue Sea", "White Rock"),
 ("Montenegro became independent from Serbia in…?", "2006", "1991", "1945", "2013"),
 ("Montenegro's fjord-like bay with a walled old town?", "Bay of Kotor", "Bay of Budva", "Ulcinj Bay", "Tivat Bay"),
 ("Montenegro's most common beer?", "Nikšićko", "Birra Tirana", "Ožujsko", "Jelen"),
])
add("Croatia", "Croatia", [
 ("Capital of Croatia?", "Zagreb", "Split", "Dubrovnik", "Zadar"),
 ("Croatia's currency since 2023?", "The euro", "Kuna", "Dinar", "Lek"),
 ("Croatia's popular beers?", "Ožujsko and Karlovačko", "Nikšićko", "Laško", "Birra Tirana"),
 ("Dubrovnik doubled as which city in Game of Thrones?", "King's Landing", "Winterfell", "Braavos", "Meereen"),
 ("Split's old town is built inside which Roman emperor's palace?", "Diocletian", "Hadrian", "Augustus", "Constantine"),
 ("Croatia's famous national park of terraced lakes and waterfalls?", "Plitvice Lakes", "Krka only", "Paklenica", "Mljet"),
 ("Which accessory is said to come from Croatian soldiers?", "The necktie (cravat)", "The beret", "The scarf", "The bow tie"),
 ("Croatia reached which men's World Cup final?", "2018", "1998", "2022", "2010"),
 ("Which spotted dog breed is named after a Croatian region?", "The Dalmatian", "The Istrian Hound", "The Posavac", "The Tornjak"),
])
