# (category, place, question, answer, wrong1, wrong2, wrong3)
F = []
def add(cat, place, rows):
    for r in rows: F.append((cat, place) + tuple(r))

# ===================== EGYPT =====================
add("Egypt", "Egypt basics", [
 ("Capital of Egypt?", "Cairo", "Alexandria", "Luxor", "Giza"),
 ("Main language of Egypt?", "Arabic", "Coptic", "French", "Berber"),
 ("Egypt's currency?", "Egyptian pound", "Egyptian dinar", "Dirham", "Riyal"),
 ("The best-known local Egyptian lager, unrelated to the Belgian brand of the same name?", "Stella", "Sakara Gold", "Luxor", "Heineken"),
 ("Egypt's cheap, beloved street dish of rice, lentils, macaroni, chickpeas and spicy tomato sauce?", "Koshari", "Ful medames", "Shawarma", "Tagine"),
 ("Which canal, opened in 1869, links the Mediterranean to the Red Sea?", "Suez Canal", "Panama Canal", "Corinth Canal", "Nile Canal"),
 ("Which artefact let Champollion crack hieroglyphs in 1822?", "The Rosetta Stone", "The Narmer Palette", "The Dead Sea Scrolls", "The Book of the Dead"),
 ("Where is the Rosetta Stone kept today?", "The British Museum, London", "The Egyptian Museum, Cairo", "The Louvre, Paris", "Grand Egyptian Museum, Giza"),
 ("The Rosetta Stone carries the same decree in hieroglyphs, Demotic and which third script?", "Ancient Greek", "Latin", "Aramaic", "Coptic"),
 ("Which giant temples were cut apart and moved uphill in the 1960s to escape Lake Nasser?", "Abu Simbel", "Karnak", "Philae's Luxor Temple", "Edfu"),
 ("The Aswan High Dam, finished in 1970, created which huge reservoir?", "Lake Nasser", "Lake Victoria", "Lake Qarun", "Lake Tana"),
 ("Roughly how far does the Nile run?", "About 6,650 km", "About 3,200 km", "About 9,800 km", "About 4,400 km"),
])
add("Egypt", "Pyramids", [
 ("What's generally counted as the first pyramid ever built?", "The Step Pyramid of Djoser", "The Great Pyramid of Khufu", "The Red Pyramid", "The Bent Pyramid"),
 ("Who's credited as architect of Djoser's Step Pyramid?", "Imhotep", "Senenmut", "Hemiunu", "Ramses"),
 ("Where is the Step Pyramid of Djoser?", "Saqqara", "Giza", "Dahshur", "Luxor"),
 ("Roughly when was the Step Pyramid built?", "Around 2670 BC", "Around 1300 BC", "Around 3500 BC", "Around 500 BC"),
 ("In the usual early sequence, which pyramid comes second, the one that later partly collapsed?", "Meidum Pyramid", "Red Pyramid", "Pyramid of Khafre", "Pyramid of Menkaure"),
 ("Which pyramid changes angle halfway up because the builders feared it would collapse?", "The Bent Pyramid", "The Red Pyramid", "The Meidum Pyramid", "The Step Pyramid"),
 ("Which is considered the first true smooth-sided pyramid?", "The Red Pyramid", "The Bent Pyramid", "The Step Pyramid", "The Great Pyramid"),
 ("Which pharaoh built the Meidum, Bent and Red pyramids?", "Sneferu", "Khufu", "Djoser", "Ramses II"),
 ("How was Sneferu related to Khufu, builder of the Great Pyramid?", "His father", "His son", "His brother", "No relation"),
 ("Where are the Bent and Red pyramids?", "Dahshur", "Giza", "Saqqara", "Abydos"),
 ("Who built the Great Pyramid of Giza?", "Khufu", "Khafre", "Menkaure", "Sneferu"),
 ("Roughly when was the Great Pyramid finished?", "Around 2560 BC", "Around 1500 BC", "Around 3200 BC", "Around 800 BC"),
 ("The Great Pyramid's original height?", "About 146 m", "About 98 m", "About 210 m", "About 75 m"),
 ("For about how long was the Great Pyramid the tallest human-made structure on Earth?", "About 3,800 years", "About 500 years", "About 1,200 years", "About 2,000 years"),
 ("The three main Giza pyramids belong to Khufu, Khafre and…?", "Menkaure", "Sneferu", "Djoser", "Tutankhamun"),
 ("Which is the smallest of the three main Giza pyramids?", "Menkaure's", "Khafre's", "Khufu's", "They're identical"),
 ("Why does Khafre's pyramid look taller than Khufu's?", "It sits on higher ground and keeps some casing at the top", "It is actually taller", "It was rebuilt by the Romans", "It's closer to the road"),
 ("The Great Pyramid is the only one of the Seven Wonders of the Ancient World that…?", "Still stands", "Was in Egypt", "Was built by slaves", "Was made of marble"),
 ("What does the evidence say about who built the Giza pyramids?", "Paid, fed Egyptian labour crews", "Hebrew slaves", "Roman prisoners", "Foreign mercenaries"),
])
add("Egypt", "Sphinx", [
 ("Which pharaoh is the Great Sphinx most often linked to?", "Khafre", "Khufu", "Ramses II", "Tutankhamun"),
 ("The Great Sphinx has the body of which animal?", "A lion", "A jackal", "A bull", "A falcon"),
 ("Roughly how long is the Great Sphinx?", "About 73 m", "About 20 m", "About 150 m", "About 45 m"),
 ("The popular story that Napoleon's troops shot off the Sphinx's nose is…?", "A myth, drawings show it missing earlier", "True, in 1798", "True, but it was the British", "Proven by a cannonball found inside"),
 ("The Sphinx was carved mostly from…?", "The living bedrock of the plateau", "Granite blocks from Aswan", "Marble from Greece", "Mud brick"),
])
add("Egypt", "Valley of the Kings", [
 ("The Valley of the Kings sits across the Nile from which modern city?", "Luxor", "Aswan", "Cairo", "Alexandria"),
 ("The Valley of the Kings was the burial ground of which era's pharaohs?", "The New Kingdom", "The Old Kingdom", "The Ptolemies", "The Romans"),
 ("Why did New Kingdom pharaohs switch from pyramids to hidden rock tombs?", "To stop tomb robbers", "They ran out of stone", "A Roman ban", "Pyramids kept flooding"),
 ("Who discovered Tutankhamun's tomb in 1922?", "Howard Carter", "Flinders Petrie", "Lord Carnarvon alone", "Zahi Hawass"),
 ("Who funded Howard Carter's search for Tutankhamun?", "Lord Carnarvon", "King George V", "The Egyptian government", "The British Museum"),
 ("Tutankhamun's tomb number in the Valley of the Kings?", "KV62", "KV1", "KV17", "KV5"),
 ("About how old was Tutankhamun when he became pharaoh?", "About 9", "About 18", "About 25", "About 3"),
 ("About how old was Tutankhamun when he died?", "About 18 or 19", "About 30", "About 45", "About 12"),
 ("Why is Tutankhamun so famous despite being a minor king?", "His tomb was found almost intact", "He built the most temples", "He reigned 60 years", "He defeated the Hittites"),
 ("Tutankhamun's innermost coffin is made of…?", "Solid gold", "Gilded wood", "Silver", "Alabaster"),
 ("Tutankhamun's father is widely thought to be which 'heretic' pharaoh who worshipped one sun god?", "Akhenaten", "Ramses II", "Thutmose III", "Khufu"),
 ("What was the 'curse of the pharaohs' story fuelled by?", "Lord Carnarvon's death months after the tomb opened", "Carter's death inside the tomb", "A plague in Luxor", "An inscription in the tomb"),
])
add("Egypt", "Karnak", [
 ("Karnak Temple was mainly dedicated to which god?", "Amun-Ra", "Anubis", "Osiris", "Horus"),
 ("What's Karnak famous for in size?", "One of the largest religious complexes ever built", "The smallest temple in Egypt", "The tallest obelisk ever carved", "The oldest pyramid"),
 ("Karnak's Great Hypostyle Hall has how many giant columns?", "134", "48", "300", "12"),
 ("Karnak was linked to Luxor Temple by which avenue?", "The Avenue of Sphinxes", "The Avenue of the Dead", "The Royal Road", "The Nile Promenade"),
 ("Roughly how long did pharaohs keep adding to Karnak?", "About 2,000 years", "About 50 years", "About 200 years", "About 5,000 years"),
])
add("Egypt", "Hatshepsut", [
 ("Hatshepsut's mortuary temple is at which site?", "Deir el-Bahari", "Saqqara", "Karnak", "Abu Simbel"),
 ("What was unusual about Hatshepsut?", "She ruled as a full female pharaoh", "She was a foreign queen", "She was a child king", "She ruled from Rome"),
 ("How was Hatshepsut often shown in statues?", "With a pharaoh's false beard", "As a lioness", "With a falcon head", "Seated beside her husband"),
 ("Hatshepsut's famous trade expedition went to which land?", "Punt", "Nubia", "Troy", "Persia"),
 ("Who's credited as the architect of Hatshepsut's temple?", "Senenmut", "Imhotep", "Hemiunu", "Amenhotep"),
 ("Who later tried to erase Hatshepsut's images and name?", "Thutmose III, her successor", "Ramses II", "Cleopatra", "Akhenaten"),
])
add("Egypt", "Alexander & Ptolemies", [
 ("Alexander the Great took Egypt in 332 BC from which empire?", "The Persian Empire", "The Roman Republic", "The Hittite Empire", "The Assyrians"),
 ("Which desert oracle did Alexander visit, where he was hailed as son of Amun?", "Siwa", "Delphi", "Dodona", "Faiyum"),
 ("Alexandria was founded by Alexander in roughly which year?", "331 BC", "48 BC", "1200 BC", "AD 30"),
 ("After Alexander died, which of his generals took Egypt and founded a dynasty?", "Ptolemy", "Seleucus", "Antigonus", "Cassander"),
 ("The Lighthouse of Alexandria stood on which island?", "Pharos", "Rhodes", "Crete", "Elephantine"),
 ("What made the Library of Alexandria so significant?", "It aimed to collect all the world's written knowledge", "It was the first library ever", "It held only religious texts", "It was built by Caesar"),
 ("The Library tried to gather every book by…", "Copying scrolls from ships in the harbour", "Buying only Roman books", "Banning foreign texts", "Writing them from memory"),
 ("Which mathematician of Alexandria estimated Earth's circumference remarkably well?", "Eratosthenes", "Pythagoras", "Archimedes", "Plato"),
 ("Was the Library destroyed in one single fire?", "No, it declined over centuries", "Yes, by Caesar in 48 BC", "Yes, by Napoleon", "Yes, by an earthquake"),
 ("Cleopatra VII belonged to which family?", "The Ptolemies, of Macedonian Greek descent", "Native Egyptian royalty", "A Roman noble family", "Persian nobility"),
 ("Cleopatra was famous as the first of her dynasty to…?", "Learn to speak Egyptian", "Visit Rome", "Build a pyramid", "Rule alone"),
])
add("Egypt", "Caesar & Cleopatra", [
 ("How, according to Plutarch, did Cleopatra get to Julius Caesar past her brother's guards?", "Smuggled in a bedding sack, popularly a rug", "Disguised as a soldier", "Through a tunnel", "Swimming the harbour"),
 ("Who carried Cleopatra in to meet Caesar?", "Apollodorus the Sicilian", "Mark Antony", "Ptolemy XIII", "Brutus"),
 ("In what year did Cleopatra meet Caesar in Alexandria?", "48 BC", "31 BC", "100 BC", "AD 14"),
 ("Cleopatra was fighting a civil war against her brother. Who was he?", "Ptolemy XIII", "Caesarion", "Ptolemy I", "Octavian"),
 ("Cleopatra's son with Julius Caesar?", "Caesarion", "Augustus", "Alexander Helios", "Ptolemy XIV"),
 ("After Caesar's murder, Cleopatra allied with and married which Roman?", "Mark Antony", "Octavian", "Pompey", "Brutus"),
 ("Which sea battle in 31 BC did Antony and Cleopatra lose to Octavian?", "Actium", "Salamis", "Lepanto", "Alexandria"),
 ("How does tradition say Cleopatra died in 30 BC?", "Bitten by an asp, a cobra", "Executed in Rome", "Drowned in the Nile", "Killed in battle"),
 ("What happened to Egypt after Cleopatra's death?", "It became a Roman province", "The Persians retook it", "Caesarion ruled 40 years", "It became independent"),
 ("Why was Pompey the Great beheaded on arriving in Egypt in 48 BC?", "Ptolemy XIII's court hoped to win Caesar's favour", "Cleopatra ordered it", "He lost a duel", "Caesar ordered it"),
])
add("Egypt", "Hawara Labyrinth", [
 ("The legendary Egyptian 'Labyrinth' is at Hawara, beside the pyramid of which pharaoh?", "Amenemhat III", "Khufu", "Ramses II", "Djoser"),
 ("Which Greek historian wrote that the Labyrinth surpassed even the pyramids?", "Herodotus", "Plutarch", "Homer", "Thucydides"),
 ("The Hawara Labyrinth is in which region of Egypt?", "The Faiyum", "The Sinai", "Upper Nubia", "The Nile Delta"),
 ("Why can't you see the Labyrinth like the pyramids?", "It's buried and was largely quarried away", "It's underwater", "It's inside a military base", "It never existed"),
 ("How was the Labyrinth's buried layout probed in 2008?", "Ground-penetrating scans by the Mataha expedition", "A full excavation", "Satellite photos only", "Robots inside the pyramid"),
])

# ===================== ROME / ITALY =====================
add("Italy", "Colosseum", [
 ("The Colosseum's official ancient name?", "The Flavian Amphitheatre", "The Circus Maximus", "The Pantheon", "The Theatre of Pompey"),
 ("Which emperor began the Colosseum around AD 70–72?", "Vespasian", "Nero", "Augustus", "Hadrian"),
 ("Which emperor opened the Colosseum in AD 80?", "Titus", "Caligula", "Trajan", "Marcus Aurelius"),
 ("How long did the Colosseum's opening games last?", "100 days", "7 days", "1 year", "1 day"),
 ("About how many spectators could the Colosseum hold?", "About 50,000", "About 5,000", "About 250,000", "About 15,000"),
 ("The Colosseum was built on the site of which emperor's drained private lake?", "Nero's, at his Golden House", "Augustus'", "Caligula's", "Hadrian's"),
 ("What was the hypogeum?", "The underground tunnels and cages beneath the arena floor", "The emperor's box", "A shade awning", "The gladiator school"),
 ("What was the velarium?", "A huge retractable awning for shade", "A wooden arena floor", "A lift for animals", "A drainage system"),
 ("How did animals and scenery appear suddenly in the arena?", "Lifts and trapdoors from the hypogeum", "Ramps from the street", "Cranes over the walls", "They were walked in"),
 ("Where does the word 'arena' come from?", "Latin for sand, spread to soak up blood", "Greek for battle", "The name of a gladiator", "A Roman god"),
 ("What was a typical order of a day at the Colosseum?", "Animal hunts in the morning, executions at midday, gladiators in the afternoon", "Gladiators all day", "Chariot races then plays", "Executions only"),
 ("What were 'venationes'?", "Staged wild animal hunts", "Naval battles", "Chariot races", "Poetry contests"),
 ("Which exotic animals were brought to the arena?", "Lions, leopards, bears, elephants and more", "Only dogs and bulls", "Only lions", "No animals were used"),
 ("Who's often blamed for the Colosseum's missing outer ring?", "Earthquakes, then centuries of stone robbing", "Napoleon's army", "WWII bombing", "A fire in AD 80"),
 ("How was the crowd seated?", "Strictly by social class", "First come, first served", "Women at the front", "By ticket price only"),
 ("What was a naumachia?", "A staged naval battle", "A gladiator's oath", "A lion hunt", "A chariot race"),
])
add("Italy", "Gladiators", [
 ("Who were most gladiators?", "Slaves, prisoners of war and condemned criminals", "Roman senators", "Only volunteers", "Priests"),
 ("Did free men ever choose to become gladiators?", "Yes, some volunteered for fame and money", "Never", "Only emperors", "Only women"),
 ("A gladiator armed with a net and trident was a…?", "Retiarius", "Murmillo", "Secutor", "Thraex"),
 ("The heavily armed gladiator usually matched against the net-man?", "Secutor", "Retiarius", "Hoplomachus", "Eques"),
 ("Gladiator with a big rectangular shield and a fish-crested helmet?", "Murmillo", "Retiarius", "Thraex", "Dimachaerus"),
 ("Gladiator with a small shield and a curved short sword?", "Thraex", "Murmillo", "Retiarius", "Secutor"),
 ("What did a gladiator receive to mark his freedom?", "A wooden sword, the rudis", "A gold crown", "A Roman toga", "A horse"),
 ("Who decided whether a beaten gladiator lived?", "The emperor or games' host, swayed by the crowd", "The winning gladiator", "A priest", "A referee"),
 ("The idea that 'thumbs down' meant death is…?", "Uncertain, the real gesture is debated", "Proven by many sources", "From the Bible", "Definitely true"),
 ("Did most gladiator fights end in death?", "No, many ended with the loser spared", "Yes, always", "Only on holidays", "Only for retiarii"),
 ("Which gladiator led a huge slave revolt in 73–71 BC?", "Spartacus", "Commodus", "Maximus", "Crixus"),
 ("Which emperor fought in the arena himself, shocking Rome?", "Commodus", "Augustus", "Trajan", "Hadrian"),
 ("What diet did gladiators reportedly eat, earning the nickname 'barley men'?", "Mostly barley and beans", "Mostly meat", "Mostly fish", "Mostly bread and wine"),
 ("Gladiators trained at schools called…?", "Ludi", "Thermae", "Fora", "Insulae"),
 ("What did gladiators supposedly say before fighting, according to Suetonius?", "'Those who are about to die salute you'", "'Glory to Rome'", "'Strength and honour'", "'For the Republic'"),
])
add("Italy", "Aqueducts", [
 ("What powered Roman aqueducts?", "Gravity, with a gentle steady slope", "Pumps worked by slaves", "Windmills", "Steam"),
 ("Rome's first aqueduct, built in 312 BC?", "Aqua Appia", "Aqua Virgo", "Aqua Claudia", "Aqua Marcia"),
 ("Which ancient aqueduct still feeds the Trevi Fountain?", "Aqua Virgo", "Aqua Appia", "Aqua Claudia", "Aqua Traiana"),
 ("Who built the Aqua Virgo in 19 BC?", "Agrippa", "Nero", "Julius Caesar", "Vespasian"),
 ("How many major aqueducts eventually supplied ancient Rome?", "11", "2", "40", "5"),
 ("Which famous three-tiered Roman aqueduct bridge is in southern France?", "Pont du Gard", "Pont Neuf", "Segovia Bridge", "Ponte Vecchio"),
 ("Were most aqueduct channels on tall arches?", "No, most ran underground", "Yes, all of them", "They floated on rivers", "They were all pipes on the surface"),
])
add("Italy", "Monuments of Rome", [
 ("Which architect designed the Trevi Fountain, finished in 1762?", "Nicola Salvi", "Bernini", "Michelangelo", "Borromini"),
 ("The tradition at the Trevi Fountain?", "Toss a coin over your shoulder to return to Rome", "Drink the water for luck", "Make a wish and swim", "Kiss the statue"),
 ("Where does the Trevi Fountain coin money go?", "To charity, through Caritas", "To the Vatican bank", "To the city's mayor", "To the fountain cleaners only"),
 ("Who's the central figure of the Trevi Fountain?", "Oceanus", "Neptune's son Triton alone", "Jupiter", "Bacchus"),
 ("What was the Roman Forum?", "The centre of public, political and religious life", "The gladiator school", "The emperor's palace", "A chariot track"),
 ("Who rebuilt the Pantheon into its current form around AD 125?", "Hadrian", "Augustus", "Nero", "Constantine"),
 ("What's at the top of the Pantheon's dome?", "An open hole, the oculus", "A gold statue", "A glass skylight", "A bell"),
 ("The Pantheon's dome holds what record?", "World's largest unreinforced concrete dome", "Tallest dome ever", "First stone dome", "Largest gold dome"),
 ("Which hill is Rome's legendary founding spot and later the emperors' palace site?", "Palatine Hill", "Capitoline Hill", "Aventine Hill", "Quirinal Hill"),
 ("Rome's legendary founding year?", "753 BC", "509 BC", "1000 BC", "AD 1"),
 ("Who, in legend, founded Rome after killing his twin?", "Romulus", "Remus", "Aeneas", "Numa"),
 ("What animal nursed Romulus and Remus?", "A she-wolf", "A lioness", "A goat", "A bear"),
 ("What was the Circus Maximus used for?", "Chariot racing", "Gladiator fights", "Theatre", "Public baths"),
 ("When was Julius Caesar assassinated?", "The Ides of March, 44 BC", "1 January 27 BC", "Ides of March, AD 14", "15 August 31 BC"),
 ("Where exactly was Caesar stabbed?", "In the Curia of Pompey, during a Senate meeting", "In the Colosseum", "In the Roman Forum's temple", "At his home"),
 ("Who became Rome's first emperor in 27 BC?", "Augustus", "Julius Caesar", "Nero", "Tiberius"),
 ("Which river did Caesar cross in 49 BC, starting civil war?", "The Rubicon", "The Tiber", "The Rhine", "The Po"),
 ("Which saying is linked to crossing the Rubicon?", "'The die is cast'", "'I came, I saw, I conquered'", "'Et tu, Brute?'", "'Veni, vidi, vici'"),
 ("Caesar's 'Veni, vidi, vici' boasted of a quick victory where?", "Zela, in modern Turkey", "Gaul", "Britain", "Egypt"),
 ("When did the Western Roman Empire fall?", "AD 476", "AD 1453", "AD 79", "AD 312"),
 ("Who was the last Western Roman emperor, deposed in 476?", "Romulus Augustulus", "Constantine", "Marcus Aurelius", "Justinian"),
 ("The Eastern Roman Empire lasted until which city fell in 1453?", "Constantinople", "Rome", "Ravenna", "Athens"),
 ("Which emperor legalised Christianity in AD 313?", "Constantine", "Nero", "Augustus", "Diocletian"),
 ("Roughly how big was ancient Rome's population at its peak?", "Around a million", "Around 50,000", "Around 10 million", "Around 200,000"),
 ("What was Rome's famous 'SPQR'?", "The Senate and People of Rome", "Save Peace, Quell Riots", "Soldiers Protect Quiet Rome", "A legion's name"),
])
add("Italy", "Pompeii & Vesuvius", [
 ("In what year did Vesuvius bury Pompeii?", "AD 79", "AD 410", "64 BC", "AD 1631"),
 ("Which other town was buried by the same eruption?", "Herculaneum", "Ostia", "Sorrento", "Capri"),
 ("Who wrote the eyewitness account of the eruption?", "Pliny the Younger", "Seneca", "Cicero", "Tacitus"),
 ("What happened to Pliny the Elder in the eruption?", "He died leading a rescue by sea", "He escaped to Rome", "He wrote the account", "He was buried in Pompeii"),
 ("How were the famous body shapes at Pompeii made?", "Plaster poured into voids left in the ash", "They're petrified bodies", "Carved by Romans", "Wax models"),
 ("Who developed the plaster cast technique in the 1860s?", "Giuseppe Fiorelli", "Howard Carter", "Leonardo da Vinci", "Garibaldi"),
 ("What killed most victims at Pompeii?", "Pyroclastic surges of hot gas and ash", "Lava flows", "A tsunami", "Earthquakes"),
 ("When did Vesuvius last erupt?", "1944", "1871", "2010", "1631"),
 ("Which city sits at the foot of Vesuvius?", "Naples", "Rome", "Bari", "Palermo"),
 ("The traditional date for the eruption is 24 August. What does newer evidence suggest?", "Probably later, around October", "Probably June", "It was in 69 AD", "It was in winter 80 AD"),
])
add("Italy", "Italy around", [
 ("Capital of Italy?", "Rome", "Milan", "Florence", "Naples"),
 ("Italy's best-known mass-market beers?", "Peroni and Moretti", "Stella and Leffe", "Mahou and Damm", "Sagres and Super Bock"),
 ("In what year was Italy unified as one kingdom?", "1861", "1492", "1946", "1789"),
 ("When did Italy become a republic, voting out the monarchy?", "1946", "1861", "1922", "1918"),
 ("Roughly how many islands is Venice built on?", "Over 100", "5", "1", "Over 1,000"),
 ("What is Venice built on?", "Wooden piles driven into the lagoon mud", "Solid bedrock", "Floating rafts", "Concrete pillars"),
 ("Venice's oldest bridge over the Grand Canal?", "Rialto Bridge", "Ponte Vecchio", "Bridge of Sighs", "Accademia Bridge"),
 ("Florence is called the birthplace of what?", "The Renaissance", "The Roman Empire", "Opera", "The Baroque"),
 ("Which banking family dominated Florence and backed Renaissance artists?", "The Medici", "The Borgia", "The Sforza", "The Este"),
 ("Who designed Florence Cathedral's great dome?", "Brunelleschi", "Michelangelo", "Bernini", "Giotto"),
 ("Where is Michelangelo's David displayed?", "Galleria dell'Accademia, Florence", "The Vatican Museums", "The Uffizi", "The Louvre"),
 ("Florence's medieval bridge lined with jewellers' shops?", "Ponte Vecchio", "Rialto", "Ponte Sant'Angelo", "Ponte Milvio"),
 ("How many villages make up the Cinque Terre?", "Five", "Three", "Seven", "Ten"),
 ("The Cinque Terre villages: Monterosso, Vernazza, Corniglia, Manarola and…?", "Riomaggiore", "Portofino", "Positano", "Amalfi"),
 ("Which region is the Cinque Terre in?", "Liguria", "Tuscany", "Campania", "Puglia"),
 ("Which saint's relics lie in Bari's famous basilica?", "St Nicholas, the original Santa Claus", "St Peter", "St Francis", "St Mark"),
 ("Bari is the capital of which region?", "Puglia (Apulia)", "Calabria", "Sicily", "Campania"),
 ("Altamura's famous protected product?", "Its durum-wheat bread", "Its olive oil", "Its wine", "Its cheese"),
 ("What famous prehistoric find was made in a cave near Altamura in 1993?", "A Neanderthal skeleton, 'Altamura Man'", "A Roman legion's armour", "A dinosaur", "Cave paintings"),
 ("Florence's famous art gallery with Botticelli's Birth of Venus?", "The Uffizi", "The Accademia", "The Borghese", "The Brera"),
 ("Which Pisa landmark leans because of soft ground?", "The bell tower", "The cathedral", "The baptistery", "The bridge"),
])

# ===================== VATICAN =====================
add("Vatican City", "Vatican", [
 ("What's special about Vatican City's size?", "It's the world's smallest country", "It's Europe's largest city-state", "It has no borders", "It's part of Rome legally"),
 ("Which 1929 treaty made Vatican City an independent state?", "The Lateran Treaty", "The Treaty of Rome", "The Treaty of Versailles", "The Concordat of Worms"),
 ("Who signed the Lateran Treaty with the Pope?", "Mussolini's government", "Napoleon", "King Victor Emmanuel II in person", "Garibaldi"),
 ("Which force guards the Pope, since 1506?", "The Swiss Guard", "The Carabinieri", "The Papal Legion", "The French Guard"),
 ("St Peter's Basilica is built over the traditional tomb of…?", "St Peter, the first pope", "St Paul", "Constantine", "St Francis"),
 ("Who designed the dome of St Peter's Basilica?", "Michelangelo", "Bernini", "Raphael", "Brunelleschi"),
 ("Who designed the great colonnade embracing St Peter's Square?", "Bernini", "Michelangelo", "Bramante", "Borromini"),
 ("The huge bronze canopy over St Peter's main altar is Bernini's…?", "Baldachin", "Pietà", "Cathedra", "Pulpit"),
 ("Which Michelangelo statue in St Peter's is his only signed work?", "The Pietà", "David", "Moses", "Bacchus"),
 ("Who painted the Sistine Chapel ceiling, 1508–1512?", "Michelangelo", "Raphael", "Leonardo", "Botticelli"),
 ("Which famous scene on the ceiling shows God and Adam's fingers almost touching?", "The Creation of Adam", "The Last Judgment", "The Flood", "The Fall"),
 ("What fresco did Michelangelo later paint on the Sistine altar wall?", "The Last Judgment", "The School of Athens", "The Last Supper", "The Annunciation"),
 ("What signals that a new pope has been elected?", "White smoke from the Sistine Chapel chimney", "Bells only", "A red flag", "Black smoke"),
 ("The meeting of cardinals that elects a pope is called a…?", "Conclave", "Synod", "Council", "Curia"),
 ("Raphael's famous Vatican fresco of Greek philosophers?", "The School of Athens", "The Creation of Adam", "The Transfiguration", "The Last Supper"),
 ("Who was elected pope in May 2025, the first from the United States?", "Leo XIV", "Francis II", "John Paul III", "Benedict XVII"),
 ("Who was the first pope from the Americas, who died in April 2025?", "Pope Francis", "Pope Benedict XVI", "Pope John Paul II", "Pope Leo XIII"),
 ("The 1517 protest that split Western Christianity was started by…?", "Martin Luther", "Henry VIII", "John Calvin", "Galileo"),
 ("What did selling 'indulgences' help fund, angering Luther?", "Rebuilding St Peter's Basilica", "The Crusades", "The Swiss Guard", "The Sistine Chapel"),
])

# ===================== 8,000ers / NEPAL =====================
add("Nepal", "The 8,000ers", [
 ("How many mountains are over 8,000 m?", "14", "8", "21", "10"),
 ("All the 8,000 m peaks are in which two ranges?", "The Himalaya and the Karakoram", "The Andes and the Alps", "The Himalaya and the Andes", "The Rockies and the Himalaya"),
 ("How many of the 14 are in Nepal or on its border?", "8", "3", "14", "11"),
 ("Height of Everest per the 2020 survey?", "8,849 m", "8,611 m", "8,091 m", "9,100 m"),
 ("Second-highest mountain in the world?", "K2", "Kangchenjunga", "Lhotse", "Makalu"),
 ("Third-highest mountain?", "Kangchenjunga", "Lhotse", "Annapurna I", "Cho Oyu"),
 ("Height of Annapurna I?", "8,091 m", "8,849 m", "7,000 m", "8,586 m"),
 ("Annapurna I is ranked which number among the world's highest peaks?", "10th", "3rd", "14th", "1st"),
 ("Which was the first 8,000 m peak ever climbed, in 1950?", "Annapurna I", "Everest", "K2", "Nanga Parbat"),
 ("Who led and summited the first ascent of Annapurna in 1950?", "Maurice Herzog, with Louis Lachenal", "Edmund Hillary", "Reinhold Messner", "George Mallory"),
 ("Annapurna I was long notorious for…?", "The highest fatality rate of the 8,000ers", "Being the easiest 8,000er", "Never being climbed in winter", "Having a road to the top"),
 ("Lowest of the fourteen 8,000ers?", "Shishapangma", "Cho Oyu", "Broad Peak", "Annapurna I"),
 ("K2's brutal nickname?", "The Savage Mountain", "The Killer Peak", "The Widowmaker", "The Throne"),
 ("K2 sits on the border of which two countries?", "Pakistan and China", "Nepal and China", "India and Pakistan", "Nepal and India"),
 ("Who first summited Everest in 1953?", "Edmund Hillary and Tenzing Norgay", "Mallory and Irvine", "Messner and Habeler", "Herzog and Lachenal"),
 ("Where was Edmund Hillary from?", "New Zealand", "England", "Australia", "Nepal"),
 ("Who did the first ascent of Everest without supplemental oxygen in 1978?", "Reinhold Messner and Peter Habeler", "Hillary and Tenzing", "Nimsdai", "Kami Rita Sherpa"),
 ("First person to climb all 14 of the 8,000ers (1986)?", "Reinhold Messner", "Nimsdai Purja", "Jerzy Kukuczka", "Ed Viesturs"),
 ("What's the 'death zone'?", "Altitude above about 8,000 m where the body can't acclimatise", "The Khumbu Icefall", "Any glacier crevasse", "The summit ridge of K2"),
 ("Everest's dangerous shifting glacier near base camp?", "The Khumbu Icefall", "The Hillary Step", "The South Col", "The Yellow Band"),
 ("Everest's Nepali name?", "Sagarmatha", "Chomolungma", "Machapuchare", "Annapurna"),
 ("Everest's Tibetan name?", "Chomolungma", "Sagarmatha", "Kailash", "Shishapangma"),
])
add("Nepal", "Nimsdai", [
 ("Nimsdai's full name?", "Nirmal Purja", "Tenzing Norgay", "Kami Rita Sherpa", "Mingma Gyalje"),
 ("Nimsdai's 2019 mission to climb all 14 8,000ers was called…?", "Project Possible", "Project Impossible", "Mission 14", "The Death Zone Project"),
 ("How long did Project Possible take?", "6 months and 6 days", "7 years", "92 days", "2 years"),
 ("Which Netflix documentary follows Project Possible?", "14 Peaks: Nothing Is Impossible", "Free Solo", "The Alpinist", "Meru"),
 ("Before climbing, Nimsdai served in the Gurkhas and which elite UK unit?", "The Special Boat Service (SBS)", "The SAS only", "The Royal Marines band", "The Parachute Regiment"),
 ("What historic first did Nimsdai's Nepali team achieve in January 2021?", "First winter ascent of K2", "First ascent of Annapurna", "Fastest Everest climb", "First ascent of Machapuchare"),
 ("Who later beat Project Possible's time in 2023, finishing in 92 days?", "Kristin Harila with Tenjen Sherpa", "Nimsdai himself", "Reinhold Messner", "Kami Rita Sherpa"),
])
add("Nepal", "Annapurna & Nepal", [
 ("Approximate altitude of Annapurna Base Camp?", "About 4,130 m", "About 5,364 m", "About 2,800 m", "About 6,000 m"),
 ("The ring of peaks around Annapurna Base Camp is known as the…?", "Annapurna Sanctuary", "Khumbu Valley", "Mustang Circle", "Langtang Bowl"),
 ("The sacred fishtail-shaped peak above the Annapurna trek, closed to climbing?", "Machapuchare", "Ama Dablam", "Dhaulagiri", "Manaslu"),
 ("The lakeside gateway city to the Annapurna region?", "Pokhara", "Kathmandu", "Lukla", "Bhaktapur"),
 ("Capital of Nepal?", "Kathmandu", "Pokhara", "Lumbini", "Patan"),
 ("What's unique about Nepal's flag?", "It's the only non-rectangular national flag", "It has no colours", "It's square", "It's the oldest flag"),
 ("Nepal's time zone offset from UTC?", "UTC +5:45", "UTC +5:30", "UTC +6:00", "UTC +4:45"),
 ("The trekker's staple meal of lentil soup and rice?", "Dal bhat", "Momo", "Thukpa", "Biryani"),
 ("Nepal's famous steamed dumplings?", "Momos", "Gyoza", "Bao", "Samosas"),
 ("Popular Nepali beers?", "Gorkha and Everest", "Kingfisher and Taj", "Chang and Leo", "Tiger and Anchor"),
 ("Birthplace of the Buddha, in southern Nepal?", "Lumbini", "Bodh Gaya", "Pokhara", "Kathmandu"),
 ("Nepal abolished its monarchy and became a republic in…?", "2008", "1950", "1990", "2015"),
 ("Was Nepal ever colonised?", "No, never", "Yes, by Britain", "Yes, by China", "Yes, by India"),
 ("The famous Nepali soldiers in the British Army?", "Gurkhas", "Sherpas", "Sikhs", "Ghurids"),
 ("The 7.8-magnitude quake that devastated Nepal struck in…?", "2015", "2004", "2011", "1998"),
 ("Nepal's currency?", "Nepalese rupee", "Taka", "Ngultrum", "Kip"),
 ("Who are the Sherpas?", "An ethnic group of the Everest region known for mountaineering", "A Nepali army unit", "Monks", "Porters from India"),
])

# ===================== ALCATRAZ / SAN FRANCISCO =====================
add("USA", "Alcatraz", [
 ("Years Alcatraz ran as a federal prison?", "1934 to 1963", "1850 to 1900", "1900 to 1934", "1963 to 1990"),
 ("Alcatraz's nickname?", "The Rock", "The Island", "The Hole", "The Pen"),
 ("Which famous gangster served time on Alcatraz?", "Al Capone", "John Dillinger", "Bugsy Siegel", "Lucky Luciano"),
 ("The 'Birdman of Alcatraz' was…?", "Robert Stroud", "Frank Morris", "Machine Gun Kelly", "Alvin Karpis"),
 ("Who escaped in June 1962 using a raft of raincoats and dummy heads?", "Frank Morris and the Anglin brothers", "Al Capone and Kelly", "Stroud and Karpis", "Three guards"),
 ("What happened to the 1962 escapees?", "Never found, officially presumed drowned", "Caught next day", "Shot in the water", "Turned themselves in"),
 ("What did the 1962 escapees make dummy heads from?", "Soap, toilet paper and real hair", "Wax and cloth", "Bread and paint", "Clay from the yard"),
 ("Why did Alcatraz close in 1963?", "It was far too expensive to run", "A successful escape", "An earthquake", "A riot destroyed it"),
 ("Why was escape by swimming so dangerous?", "Freezing water and strong currents", "Sharks guarded it", "The bay was 20 km wide", "Mines in the water"),
 ("Who occupied Alcatraz from 1969 to 1971?", "Native American activists", "Hippies", "The US Navy", "Squatters from Oakland"),
 ("Before the prison era, Alcatraz was a…?", "Military fort and military prison", "Lighthouse only", "Leper colony", "Fishing village"),
 ("Alcatraz had the first lighthouse on which coast?", "The US West Coast", "The US East Coast", "Hawaii", "Alaska"),
 ("The 1946 two-day standoff on the island is called…?", "The Battle of Alcatraz", "The Rock Riot", "The Bay Siege", "The Great Break"),
 ("How many inmates were officially ever confirmed to have successfully escaped?", "None", "Twelve", "Three", "Thirty-six"),
 ("Which Clint Eastwood film tells the 1962 escape?", "Escape from Alcatraz", "The Rock", "Birdman of Alcatraz", "Dirty Harry"),
])
add("USA", "San Francisco", [
 ("When did the Golden Gate Bridge open?", "1937", "1906", "1964", "1915"),
 ("The Golden Gate Bridge's colour is officially called…?", "International Orange", "Golden Red", "Pacific Rust", "Bay Orange"),
 ("The disaster that destroyed much of San Francisco in 1906?", "An earthquake and the fires after it", "A tsunami", "A hurricane", "A gold-mine collapse"),
 ("San Francisco boomed after gold was found in California in…?", "1848, the rush of '49", "1906", "1776", "1920"),
 ("What's special about San Francisco's cable cars?", "The last manually operated cable car system in the world", "They're powered by horses", "They're underground", "They're the oldest trams in Europe"),
 ("San Francisco's famously crooked street?", "Lombard Street", "Market Street", "Haight Street", "Castro Street"),
 ("The tech region south of San Francisco?", "Silicon Valley", "Napa Valley", "Death Valley", "Central Valley"),
 ("The San Francisco district of the 1967 'Summer of Love'?", "Haight-Ashbury", "Nob Hill", "Mission", "SoMa"),
 ("San Francisco's historic beer brand, whose brewery closed in 2023?", "Anchor Steam", "Sierra Nevada", "Budweiser", "Lagunitas"),
])
