# Quality pass over the knowledge bank, applied by compile_bank.py.
# Keyed by the exact question text so card ids (a hash of the question) and review history are kept.
#   R[q] = (answer or None to keep, [3 wrong options] or None to keep, "why" explanation)
# Why: a good multiple-choice item has options of similar length and plausibility, otherwise the
# longest option gives the answer away. Detail moves into "why", shown after answering: explaining
# the answer (elaborative feedback) is what makes a fact stick.
R = {
 "Who is Andrew Huberman?": ("Stanford neuroscientist and podcaster", ["Harvard cardiologist and author", "Olympic rowing coach", "Former Navy SEAL instructor"],
   "He runs a neurobiology lab at Stanford School of Medicine and hosts the Huberman Lab podcast, one of the world's most popular science shows."),
 "Huberman's number-one daily habit?": ("Morning sunlight in your eyes", ["Cold shower before bed", "Fasting until noon", "10,000 steps before work"],
   "Viewing outdoor light soon after waking sets the circadian clock: it times the morning cortisol pulse and the evening melatonin rise."),
 "Which Netflix documentary follows Project Possible?": ("14 Peaks", ["Free Solo", "The Alpinist", "Meru"],
   "14 Peaks: Nothing Is Impossible (2021) follows Nimsdai Purja climbing all fourteen 8,000 m peaks in just over six months."),
 "What does early light do to cortisol?": ("Times a healthy morning peak", ["Suppresses it for the day", "Delays it until evening", "Has no measurable effect"],
   "A cortisol peak early in the day is healthy: it drives alertness. The same peak late in the day is linked to anxiety and poor sleep."),
 "Where does the word 'robot' come from?": ("A 1920 Czech play", ["An Isaac Asimov story", "A Japanese toy company", "Leonardo da Vinci's notes"],
   "Karel Čapek's play R.U.R. (Rossum's Universal Robots) introduced the word, from Czech 'robota', forced labour. His brother Josef suggested it."),
 "Why does that early cortisol pulse help sleep later?": ("It starts a melatonin timer", ["It burns off excess energy", "It blocks adenosine build-up", "It lowers body temperature"],
   "The morning pulse sets a clock: melatonin release follows roughly 12 to 16 hours later, so you get sleepy at a sensible time."),
 "What does Huberman say bright light between about 10pm and 4am does?": ("Suppresses melatonin", ["Deepens slow-wave sleep", "Raises testosterone", "Lowers resting heart rate"],
   "Bright light in the middle of the night shuts down melatonin and, he argues, can disturb dopamine and mood. Dim, low, warm light is the fix."),
 "Escobar's ranch that left Colombia with a growing population of…?": ("Hippos", ["Lions", "Elephants", "Giraffes"],
   "Escobar imported four hippos to Hacienda Nápoles. After his death they bred in the Magdalena River; there are now well over 100."),
 "Roughly how many islands is Venice built on?": (None, ["About 12", "About 40", "Over 1,000"],
   "Venice spans about 118 small islands linked by more than 400 bridges over its canals."),
 "What is Venice built on?": ("Wooden piles in the mud", ["Solid limestone bedrock", "Floating timber rafts", "Concrete pillars"],
   "Millions of alder, oak and larch piles were driven into the lagoon mud. Starved of oxygen underwater, the wood petrified rather than rotted."),
 "What's the 'death zone'?": ("Altitude above about 8,000 m", ["The Khumbu Icefall", "Any crevassed glacier", "K2's summit ridge"],
   "Above roughly 8,000 m there's too little oxygen to acclimatise: the body deteriorates hour by hour, so climbers move up and down fast."),
 "What's machine learning, in one line?": ("Learning patterns from data", ["Robots that build machines", "Very fast hand-coded rules", "Programs that never change"],
   "Instead of a programmer writing every rule, a model is shown many examples and adjusts itself to predict or decide from them."),
 "Roughly how much does cold water immersion raise dopamine in the study he cites?": ("About 2.5 times", ["About 10%", "About 100 times", "About 25%"],
   "In a 2000 study, an hour in 14 °C water raised dopamine about 250% above baseline, and it stayed elevated for hours."),
 "Huberman's suggested weekly cold exposure total?": ("About 11 minutes", ["About 2 hours", "About 1 minute", "About 60 minutes a day"],
   "From Susanna Søberg's research: roughly 11 minutes of deliberate cold per week, split across 2 to 4 sessions."),
 "How far east did Alexander's army march before turning back?": ("India's Beas River", ["China's Yellow River", "Egypt's Nile delta", "Arabia's Red Sea coast"],
   "At the Hyphasis (Beas) in 326 BC his exhausted army mutinied and refused to go further, so he turned back."),
 "The 'Søberg principle' says to end on…?": ("Cold", ["Heat", "A warm shower", "A stretch"],
   "Finishing cold forces your body to rewarm itself, which burns more energy and builds cold tolerance."),
 "Which saint's relics lie in Bari's famous basilica?": ("St Nicholas", ["St Peter", "St Francis", "St Mark"],
   "Sailors from Bari took the relics from Myra (in modern Turkey) in 1087. St Nicholas is the original Santa Claus."),
 "Huberman's stance on regular melatonin supplements?": ("Cautious, not for routine use", ["10 mg every night", "The best sleep aid there is", "Fine, but only with coffee"],
   "Over-the-counter doses are often far higher than what the body makes, and he points to possible effects on other hormones."),
 "San Francisco boomed after gold was found in California in…?": ("1848", ["1906", "1776", "1920"],
   "Gold was found at Sutter's Mill in January 1848; the rush peaked in 1849, hence the 'Forty-Niners'."),
 "The NASA rover that landed on Mars in 2021 carrying a small helicopter?": ("Perseverance", ["Curiosity", "Spirit", "Opportunity"],
   "Perseverance carried Ingenuity, which made the first powered flight on another planet in April 2021."),
 "Who are the Sherpas?": ("An ethnic group of the Everest region", ["A Nepali army regiment", "An order of Tibetan monks", "Porters hired from India"],
   "Sherpa is an ethnic group, not a job title. They migrated from Tibet centuries ago and are famed for high-altitude mountaineering."),
 "Why does Huberman suggest using low lamps instead of overhead lights at night?": ("Light from above hits key retina cells", ["Lamps use less electricity", "Overhead bulbs are bluer", "It's easier to read by"],
   "The light-sensing ganglion cells that signal 'daytime' sit mostly in the lower retina, so they look upward. Light from below barely triggers them."),
 "Which national park holds Laguna 69 and the Santa Cruz trek?": ("Huascarán", ["Manu", "Colca", "Paracas"],
   "Huascarán National Park protects most of the Cordillera Blanca, including Peru's highest peak."),
 "Quechua famously lacks a simple word for…?": ("Goodbye", ["Thank you", "Water", "Mother"],
   "People say 'tupananchiskama', roughly 'until we meet again'."),
 "Who later tried to erase Hatshepsut's images and name?": ("Thutmose III", ["Ramses II", "Akhenaten", "Tutankhamun"],
   "Her stepson and successor, probably late in his reign, to secure his own line's legitimacy."),
 "What did Napoleon sell to the US in 1803?": ("Louisiana", ["Florida", "Quebec", "Texas"],
   "The Louisiana Purchase roughly doubled the size of the United States for about $15 million."),
 "Which visual trick does Huberman say calms the stress response?": ("Panoramic vision", ["Staring at one point", "Closing one eye", "Rapid blinking"],
   "Widening your gaze to take in the whole scene (rather than focusing tightly) is linked to lower arousal in the brainstem."),
 "Is short-term (acute) stress always harmful?": ("No, it can sharpen you", ["Yes, always", "Only in the morning", "Only for athletes"],
   "Brief stress can boost focus and immune readiness. It's chronic, unrelenting stress that does the damage."),
 "Higher heart rate variability (HRV) generally signals…?": ("Good recovery", ["Illness", "Dehydration", "Overtraining"],
   "HRV is the beat-to-beat variation in heart rhythm. Higher usually means a relaxed, adaptable nervous system."),
 "What does Huberman say short pauses of about 10 seconds during learning allow?": ("Fast replay of what you learned", ["Muscle recovery", "Cortisol to reset", "Eyes to refocus"],
   "During brief rests the hippocampus replays the material at high speed, about ten times faster, which helps it stick."),
 "Huacachina is…?": ("A desert oasis", ["A glacier lake", "An Inca fortress", "A surf town"],
   "A small lagoon near Ica ringed by huge sand dunes, famous for sandboarding and dune buggies."),
 "Dopamine is mainly the molecule of…?": ("Motivation", ["Sleep", "Pain", "Digestion"],
   "It drives wanting and pursuit more than pleasure itself, which is why anticipation can feel better than the reward."),
 "To keep motivation high, Huberman suggests rewarding yourself…?": ("Unpredictably", ["Every single time", "Only after a full week", "Only on Sundays"],
   "Intermittent rewards keep dopamine responsive. Reward every time and the baseline creeps up until nothing feels special."),
 "Roughly what share of the body's serotonin is made in the gut?": ("About 90%", ["About 5%", "About 50%", "About 25%"],
   "Most serotonin is made by gut cells. It mostly works there and doesn't cross into the brain directly."),
 "La Paz's cable car network?": ("Mi Teleférico", ["The Metrocable", "Los Ascensores", "Teleférico Sur"],
   "Opened in 2014, it's the world's largest urban cable car network, linking La Paz with El Alto."),
 "Why was Pompey the Great beheaded on arriving in Egypt in 48 BC?": ("To win Caesar's favour", ["Cleopatra ordered it", "He lost a duel", "Caesar ordered it"],
   "Ptolemy XIII's advisers thought killing Caesar's rival would please him. Caesar reportedly wept when shown Pompey's head."),
 "Roughly how much Zone 2 per week does Huberman suggest?": ("About 150 to 200 minutes", ["About 10 minutes", "About 15 hours", "About 30 minutes"],
   "Zone 2 is steady effort where you can still talk. A few hours a week builds the aerobic base that supports everything else."),
 "What does VO2 max measure?": ("Peak oxygen use", ["Lung size", "Maximum heart rate", "Muscle strength"],
   "The most oxygen your body can take in and use during all-out exercise. It's one of the strongest predictors of longevity."),
 "What happened to Turing in 1952?": ("Convicted for being gay", ["He was knighted", "He was made head of MI6", "He moved to America"],
   "Convicted of 'gross indecency', he accepted chemical castration instead of prison. He received a royal pardon in 2013."),
 "The Norwegian 4x4 protocol for VO2 max is…?": ("4 min hard, 3 min easy, x4", ["4 reps of 4 sets", "4 km at max pace", "4 hours of Zone 2"],
   "Four intervals at about 90% of max heart rate, each followed by three minutes of easy recovery."),
 "Bolivia's currency?": (None, ["Sol", "Bolívar", "Real"],
   "The boliviano replaced the peso boliviano in 1987. The sol is Peru's, the bolívar Venezuela's and the real Brazil's."),
 "Roughly how many hard sets per muscle per week for growth?": ("About 10 or more", ["About 2", "About 50", "About 100"],
   "Around 10+ challenging sets per muscle group per week is a common evidence-based target for hypertrophy."),
 "Which war cost Bolivia its coastline to Chile?": ("The War of the Pacific", ["The Chaco War", "The Acre War", "The Paraguayan War"],
   "Fought 1879 to 1884 over nitrate-rich land. Bolivia still has a navy, which trains on Lake Titicaca."),
 "The Colosseum was built on the site of which emperor's drained private lake?": ("Nero's", ["Augustus'", "Caligula's", "Hadrian's"],
   "Vespasian drained the lake of Nero's Golden House and gave the land back to the people as an arena."),
 "The 'eccentric' phase of a lift is when the muscle…?": ("Lengthens under load", ["Shortens under load", "Holds still", "Fully relaxes"],
   "Like lowering the bar in a curl. Eccentrics cause more soreness but are powerful for strength and tendon health."),
 "What was the hypogeum?": ("Tunnels beneath the arena", ["The emperor's box", "The shade awning", "The gladiator school"],
   "A two-level warren of tunnels, cages and lifts under the floor, used to send animals and scenery up through trapdoors."),
 "What did SpaceX first do with Starship's booster in October 2024?": ("Caught it with the tower", ["Landed it on Mars", "Flew it to the Moon", "Landed it on a ship"],
   "The Super Heavy booster was caught mid-air by the launch tower's 'chopstick' arms on 13 October 2024."),
 "Grip strength is linked in research to…?": ("Lower risk of death", ["Higher injury risk", "Poorer sleep", "Higher blood pressure"],
   "Large studies find stronger grip predicts lower all-cause mortality. It's a proxy for overall strength."),
 "SpaceX's long-term goal?": ("Making life multiplanetary", ["Mining asteroids", "Building space hotels", "Moon tourism"],
   "Musk founded SpaceX in 2002 with the aim of making humanity multiplanetary, starting with a city on Mars."),
 "In Huberman's weekly fitness protocol, Sunday is usually…?": ("Long endurance", ["Heavy legs", "Complete rest", "Max sprints"],
   "He uses Sunday for a long, steady Zone 2 session such as a 60 to 75 minute run, hike or ruck."),
 "Where the Rio Negro and Solimões meet without mixing for kilometres?": ("Near Manaus", ["Near Iquitos", "Near Leticia", "Near Belém"],
   "The Meeting of the Waters: dark, warm Rio Negro and pale, cooler Solimões run side by side for about 6 km."),
 "What was a typical order of a day at the Colosseum?": ("Hunts, executions, then gladiators", ["Gladiators all day", "Chariots, then plays", "Executions only"],
   "Animal hunts filled the morning, executions the midday, and the star gladiator bouts came in the afternoon."),
 "Did Musk found Tesla?": ("No, but he's called a co-founder", ["Yes, alone in 2003", "Yes, with Bill Gates", "No, he bought it in 2015"],
   "Martin Eberhard and Marc Tarpenning founded Tesla in 2003. Musk led the 2004 funding round and a 2009 settlement lets him use 'co-founder'."),
 "Who's often blamed for the Colosseum's missing outer ring?": ("Earthquakes and stone robbers", ["Napoleon's army", "WWII bombing", "A fire in AD 80"],
   "A big earthquake in 1349 brought down the south side, and the fallen stone was quarried for centuries, including for St Peter's."),
 "Who were most gladiators?": ("Slaves and prisoners", ["Roman senators", "Only volunteers", "Temple priests"],
   "Mostly slaves, prisoners of war and condemned criminals, though some free men signed up for fame and money."),
 "Did free men ever choose to become gladiators?": ("Yes, some volunteered", ["Never", "Only emperors", "Only women"],
   "Volunteers (auctorati) swore an oath giving up their rights, chasing prize money and celebrity."),
 "Who decided whether a beaten gladiator lived?": ("The host, swayed by the crowd", ["The winning gladiator", "A priest", "A referee"],
   "The editor (often the emperor) made the call, usually following the crowd's mood. Good fighters were valuable, so many were spared."),
 "Caffeine dose shown to boost exercise performance?": ("About 3 to 6 mg per kg", ["About 50 mg per kg", "About 0.1 mg per kg", "About 20 mg per kg"],
   "The sports-science consensus range is 3 to 6 mg per kg of body weight, about an hour before. Lower doses around 2 mg/kg can help too."),
 "How many men's World Cups has Argentina won?": ("Three", ["Two", "Five", "One"],
   "1978 at home, 1986 with Maradona, and 2022 in Qatar with Messi."),
 "In the Stanford fermented-food study, eating more fermented food led to…?": ("More gut diversity, less inflammation", ["Weight gain", "Worse sleep", "Higher cholesterol"],
   "In the 2021 study, people eating fermented foods daily for ten weeks gained microbe diversity and showed lower inflammatory markers."),
 "Roughly how many servings of fermented food a day does Huberman suggest?": ("About 2 to 4", ["About 20", "One a week", "About 10"],
   "Based on the Stanford study: small daily servings of things like yoghurt, kefir, kimchi or sauerkraut."),
 "A short walk after a meal does what to blood sugar?": ("Blunts the spike", ["Doubles it", "Makes it crash", "Delays it to night"],
   "Working muscles pull glucose from the blood, so even 10 minutes of walking flattens the post-meal rise."),
 "Even 1–2% dehydration can measurably hurt…?": ("Focus and performance", ["Eyesight, permanently", "Bone density", "Height"],
   "Small fluid losses are enough to reduce attention, mood and endurance, often before you feel thirsty."),
 "Valparaíso is famous for…?": ("Colourful hillside houses", ["Glaciers", "Vineyards", "Salt flats"],
   "Its hills are covered in painted houses and street art, linked by historic funicular lifts. The centre is UNESCO-listed."),
 "Why does Huberman say to let yourself shiver in cold exposure?": ("It activates brown fat", ["It warms the water", "It builds muscle", "It lowers dopamine"],
   "Shivering muscles release succinate, which signals brown fat to burn energy and make heat."),
 "What was the Roman Forum?": ("The heart of public life", ["The gladiator school", "The emperor's palace", "A chariot track"],
   "Rome's political, religious and commercial centre: temples, law courts, the Senate house and the speakers' platform."),
 "The Pantheon's dome holds what record?": ("Largest unreinforced concrete dome", ["Tallest dome ever built", "First stone dome", "Largest gilded dome"],
   "Nearly 1,900 years old and 43 m across, it is still the largest dome of unreinforced concrete in the world."),
 "Colombia's famous coffee-growing region?": ("The Eje Cafetero", ["The Llanos", "La Guajira", "Chocó"],
   "The Coffee Axis or Triangle around Manizales, Pereira and Armenia, UNESCO-listed as a cultural landscape."),
 "Caesar's 'Veni, vidi, vici' boasted of a quick victory where?": ("Zela", ["Gaul", "Britain", "Egypt"],
   "At Zela, in modern Turkey, in 47 BC he crushed Pharnaces II in about five days."),
 "What killed most victims at Pompeii?": ("Pyroclastic surges", ["Lava flows", "A tsunami", "Earthquakes"],
   "Avalanches of superheated gas and ash raced down Vesuvius. Lava played almost no part."),
 "Cinco de Mayo marks a victory over which country?": ("France", ["Spain", "The USA", "Britain"],
   "Mexican forces beat the French at the Battle of Puebla on 5 May 1862. It isn't Mexican Independence Day."),
 "What signals that a new pope has been elected?": ("White smoke", ["Bells alone", "A red flag", "Black smoke"],
   "Ballots are burned after each vote: black smoke means no decision, white smoke from the Sistine Chapel means a new pope."),
 "The hike where you camp watching the next-door volcano erupt?": ("Acatenango", ["Pacaya", "Tajumulco", "Agua"],
   "From camp on Acatenango you look straight across at Fuego, which erupts every few minutes."),
 "What did the Incas call their empire?": ("Tawantinsuyu", ["Tenochtitlan", "Qhapaq Ñan", "Inti Raymi"],
   "It means 'the four parts together', the four regions meeting at Cusco. Qhapaq Ñan was their road network."),
 "Inca stonework is famous because…?": ("Blocks fit without mortar", ["It's carved from gold", "It's one giant rock", "It uses Roman concrete"],
   "Stones were shaped to fit so tightly that a knife blade won't slip between them, and the joints flex in earthquakes."),
 "Where was Francisco Pizarro from?": ("Trujillo, Spain", ["Seville, Spain", "Lisbon, Portugal", "Genoa, Italy"],
   "Trujillo in Extremadura, a poor region that produced many conquistadors."),
 "What did Pizarro say as he drew the line, roughly?": ("Peru and riches, or Panama and poverty", ["For God and Spain, follow me", "Gold or death", "There is no turning back"],
   "On Isla del Gallo in 1527 he drew a line in the sand: cross it for Peru and riches, or go back to Panama and poverty."),
 "How many men crossed the line to stay with Pizarro?": ("13", ["160", "50", "3"],
   "They became known as 'los Trece de la Fama', the Famous Thirteen."),
 "Was the conquest mainly paid for by the King of Spain?": ("No, it was privately funded", ["Yes, entirely", "Yes, by the Pope", "No, by Portugal"],
   "The Crown granted rights and took a fifth of the treasure, but investors and the conquistadors themselves paid the costs."),
 "What ransom did Atahualpa offer for his release?": ("A room filled with gold", ["A thousand llamas", "His own crown", "The city of Cusco"],
   "One room of gold and two of silver. It was paid, and Pizarro executed him anyway in 1533."),
 "Indonesia's capital?": ("Jakarta", ["Denpasar", "Surabaya", "Bandung"],
   "A new capital, Nusantara, is being built on Borneo because Jakarta is sinking and overcrowded."),
 "Sri Lanka gave the world its first…?": ("Female prime minister", ["Female president", "Buddhist monarchy", "Tea plantation"],
   "Sirimavo Bandaranaike became prime minister in 1960."),
 "Roughly how many people were killed at the Wall?": ("At least 140", ["About 5", "About 10,000", "About 20"],
   "Research by the Berlin Wall memorial counts at least 140 people killed at the Wall or dying in connection with it between 1961 and 1989."),
 "The 'death strip' was…?": ("The no-man's land between walls", ["A street in Kreuzberg", "A Bavarian minefield", "A river crossing"],
   "A raked sand strip with watchtowers, lights and guards between the inner and outer walls, so escapers could be seen and shot."),
 "What triggered the Wall opening on 9 November 1989?": ("A botched announcement", ["A US airstrike", "A treaty signed that day", "A Gorbachev visit"],
   "Spokesman Günter Schabowski said new travel rules applied 'immediately'. Crowds rushed the checkpoints and the guards gave way."),
 "Denmark's flag, the Dannebrog, is known as…?": ("The oldest national flag in use", ["The newest flag", "The only square flag", "A copy of Sweden's"],
   "Legend dates it to 1219. It's widely cited as the oldest continuously used national flag."),
 "Why was katana steel folded many times?": ("To even out impurities", ["To make it lighter", "Purely for the pattern", "To make it magnetic"],
   "Tamahagane steel from a clay furnace was uneven. Folding spread carbon evenly and drove out slag."),
 "Sweden's popular beers?": ("Norrlands Guld and Pripps Blå", ["Carlsberg and Tuborg", "Lapin Kulta and Karhu", "Ringnes and Hansa"],
   "Carlsberg is Danish, Lapin Kulta Finnish and Ringnes Norwegian."),
 "Stockholm is spread across how many islands?": ("14", ["3", "100", "40"],
   "The city sits on 14 islands where Lake Mälaren meets the Baltic, joined by over 50 bridges."),
 "The Swede whose will created the Nobel Prizes?": ("Alfred Nobel", ["Carl Linnaeus", "Anders Celsius", "Ingvar Kamprad"],
   "The inventor of dynamite left most of his fortune to fund the prizes, first awarded in 1901."),
 "Who were the Terracotta Warriors made to guard?": ("China's first emperor", ["Genghis Khan", "Chairman Mao", "The Ming emperors"],
   "Qin Shi Huang, who unified China in 221 BC, was buried with an army of over 8,000 clay soldiers."),
 "Under the purity law beer could contain only water, barley and…?": ("Hops", ["Wheat", "Sugar", "Honey"],
   "The 1516 Reinheitsgebot named only water, barley and hops. Yeast was added once people understood fermentation."),
 "Spain's popular beers?": ("Mahou and Estrella Damm", ["Super Bock and Sagres", "Peroni and Moretti", "Quilmes and Brahma"],
   "Also Estrella Galicia and Cruzcampo. Super Bock and Sagres are Portuguese, Peroni Italian, Quilmes Argentine."),
 "Portugal's alliance with England, the world's oldest still in force, dates from…?": ("1386", ["1815", "1704", "1940"],
   "The Treaty of Windsor in 1386, building on an earlier 1373 treaty. It was invoked as recently as the Falklands War."),
 "When did the USSR join the Allies' fight?": ("1941", ["1939", "1943", "1945"],
   "In June 1941, when Germany broke their pact and invaded. In 1939 the USSR had split Poland with Germany."),
 "Albania's popular beers?": ("Birra Tirana and Korça", ["Nikšićko and Jelen", "Ožujsko and Karlovačko", "Mythos and Fix"],
   "Nikšićko is Montenegrin, Ožujsko Croatian and Mythos Greek."),
 "Why did Hoxha build so many bunkers?": ("Fear of invasion", ["Nuclear testing", "Tourism", "Grain storage"],
   "Paranoid about attack from both East and West, his regime built around 170,000 concrete bunkers across Albania."),
 "A common Albanian head gesture surprise?": ("A nod can mean no", ["A bow means no", "A wink means yes", "Thumbs up is rude"],
   "Many Albanians shake the head for yes and nod for no, the reverse of most of Europe."),
 "Japan's big beer brands?": ("Asahi and Kirin", ["Tsingtao and Snow", "Hite and Cass", "Singha and Chang"],
   "Also Sapporo and Suntory. Tsingtao is Chinese, Hite Korean and Singha Thai."),
 "Roughly how many islands make up Japan?": (None, ["4", "About 200", "About 1,000"],
   "A 2023 recount using digital maps found 14,125 islands, double the old figure. Four main islands hold most people."),
 "Sri Lanka's official legislative capital?": (None, None,
   "Sri Jayawardenepura Kotte is the official capital and seat of parliament. Colombo, next door, is the commercial capital."),
}

# Questions that only made sense straight after the card before them. Cards are shuffled and
# spaced, so every question has to stand on its own. (Rewording gives the card a new id.)
RQ = {
 "And on an overcast day?": "How long does Huberman suggest for morning light on an overcast day?",
 "His suggested weekly sauna total?": "Huberman's suggested weekly sauna total?",
 "What changed in 2006?": "What changed for Bolivia's Death Road in 2006?",
 "Historically, about how many people died on it each year?": "Historically, about how many people died on Bolivia's Death Road each year?",
 "Huacachina is…?": "Huacachina, near Ica in Peru, is…?",
}

# Explanations for answers that are worth understanding, not just recognising.
WHY = {
 "What's generally counted as the first pyramid ever built?": "Around 2670 BC Imhotep stacked six shrinking mastaba tombs at Saqqara for Djoser, creating the step pyramid that led to the smooth ones.",
 "How many mountains are over 8,000 m?": "All fourteen are in the Himalaya and Karakoram. Eight of them are in Nepal or on its border.",
 "The 1956 workshop that coined the term 'artificial intelligence'?": "John McCarthy organised the 1956 Dartmouth summer workshop and chose the name 'artificial intelligence' for its proposal.",
 "How long did Project Possible take?": "Nimsdai climbed all fourteen 8,000ers in 6 months and 6 days in 2019. The previous record was almost 8 years.",
 "How long does Huberman suggest for morning light on a clear day?": "Outdoors even a cloudy sky gives far more light than indoors, so a clear morning needs only 5 to 10 minutes.",
 "Height of Everest per the 2020 survey?": "China and Nepal's joint 2020 survey measured 8,848.86 m, including the snow cap.",
 "Second-highest mountain in the world?": "K2 (8,611 m) on the Pakistan–China border is far harder and deadlier to climb than Everest.",
 "The 2017 Google paper that introduced the Transformer?": "'Attention Is All You Need' introduced the Transformer architecture, the T in GPT and the basis of models like Claude.",
 "Which eye cells detect morning light to set your body clock?": "Intrinsically photosensitive retinal ganglion cells use melanopsin and report overall brightness to the brain's clock, not images.",
 "Which brain region is the master circadian clock?": "The suprachiasmatic nucleus sits just above where the optic nerves cross, so light can set it directly.",
 "Which pharaoh built the Meidum, Bent and Red pyramids?": "Sneferu, Khufu's father, built three pyramids as the Egyptians learned the right angle through trial and error.",
 "Escobar's notorious offer: 'plata o plomo' meant…?": "'Silver or lead': accept a bribe or be killed. It's how he corrupted or terrorised officials.",
 "What builds 'sleep pressure' in your brain the longer you're awake?": "Adenosine builds up as you burn energy through the day. Sleep clears it, and caffeine temporarily blocks its receptors.",
 "How does caffeine keep you alert?": "Caffeine fits adenosine receptors without activating them, so the 'sleepy' signal can't land. The adenosine is still there when it wears off.",
 "How long after waking does Huberman suggest delaying caffeine?": "Waiting 90 to 120 minutes lets the body clear some adenosine first, which he says avoids the early-afternoon crash.",
 "Caffeine's half-life is roughly…?": "About 5 hours, so half a 3pm coffee is still in your system at 8pm. That's why late caffeine wrecks deep sleep.",
 "The 'physiological sigh' is…?": "A double inhale through the nose re-inflates collapsed air sacs, then a long exhale offloads carbon dioxide and slows the heart.",
 "What's the physiological sigh for?": "One to three sighs is the fastest known way to bring stress down in real time, because long exhales slow the heart.",
 "What's NSDR?": "Non-sleep deep rest: lying still while guiding attention, as in yoga nidra. It's restorative without full sleep.",
 "Roughly how long is one full sleep cycle?": "About 90 minutes. Early cycles are rich in deep sleep, later ones in REM, which is why cutting the morning short costs REM.",
 "In which sleep stage is most growth hormone released?": "The biggest pulse comes in the first deep, slow-wave sleep of the night.",
 "What does alcohol before bed do to sleep?": "Alcohol is sedating, which isn't the same as sleep. It fragments the night and suppresses REM, so you wake unrefreshed.",
 "Bedroom temperature for good sleep should be…?": "Core temperature needs to drop by 1 to 3 °C to fall and stay asleep. A cool room, around 18 °C, helps.",
 "The brain's waste-clearing system that ramps up during deep sleep?": "During deep sleep, fluid flushes through brain tissue more freely, clearing waste including proteins linked to Alzheimer's.",
 "Short sleep raises which hunger hormone?": "Short sleep raises ghrelin (hunger) and lowers leptin (fullness), so you eat more, especially sugary food.",
 "The gland that releases melatonin?": "The pineal gland releases melatonin when it's dark. Light at night shuts it off.",
 "Cortisol naturally peaks about how long after waking?": "The cortisol awakening response peaks 30 to 45 minutes after waking and helps you feel alert.",
 "Box breathing uses which pattern?": "Inhale, hold, exhale, hold for equal counts, often four seconds each. It's a tool to stay calm and steady.",
 "In the 2023 Stanford study Huberman co-led, 5 minutes a day of what improved mood most?": "Cyclic sighing, with long exhales, beat box breathing, hyperventilation and mindfulness at improving mood and lowering breathing rate.",
 "Zone 2 cardio is a pace where you can…?": "You can talk in full sentences but wouldn't want to sing. It trains the mitochondria that burn fat for fuel.",
 "What actually drives muscle growth across a wide rep range (roughly 5–30)?": "As long as sets end within a few reps of failure, light and heavy loads build similar muscle.",
 "The principle of gradually increasing load, reps or difficulty?": "Muscles adapt to what you ask of them. To keep adapting, the challenge has to keep rising.",
 "What's DOMS?": "Delayed-onset muscle soreness peaks a day or two after unfamiliar or eccentric work. It isn't a sign of a good workout.",
 "Is lactate just a waste product that causes soreness?": "Lactate is a fuel the heart and muscles burn and a signalling molecule. It isn't what makes you sore.",
 "Zone 2 training especially builds more…?": "Steady aerobic work makes muscles build more and better mitochondria, the cell's power plants.",
 "Which amino acid is key for switching on muscle protein synthesis?": "Leucine acts as a trigger for muscle building, which is why protein quality matters, not just quantity.",
 "Typical daily dose of creatine monohydrate?": "About 5 g a day saturates muscle stores within a few weeks. No loading phase is needed.",
 "Finnish studies link sauna use 4–7 times a week to…?": "In a 20-year Finnish study, men using a sauna 4 to 7 times a week had far lower cardiovascular death rates than once-a-week users.",
 "Regular cold exposure increases which calorie-burning tissue?": "Brown fat is packed with mitochondria that burn energy to make heat. Cold exposure makes you build more of it.",
 "What powered Roman aqueducts?": "Gravity alone. Engineers kept a slight, steady downhill gradient over many kilometres, sometimes as little as 1 in 4,800.",
 "Were most aqueduct channels on tall arches?": "Most of the channels ran underground. The famous arches carried water only across valleys and low ground.",
 "What made the Library of Alexandria so significant?": "The Ptolemies tried to gather every book in the world, copying scrolls from ships in the harbour. It drew scholars like Eratosthenes.",
 "Was the Library destroyed in one single fire?": "Caesar's fire in 48 BC damaged it, but the Library mostly faded over centuries through lost funding and political purges.",
 "Which mathematician of Alexandria estimated Earth's circumference remarkably well?": "Eratosthenes compared the angle of the Sun's shadow in Alexandria and Syene to estimate Earth's size remarkably well.",
 "The Mongol Empire became the largest…in history?": "The Mongol Empire was the largest contiguous land empire ever. The British Empire was bigger overall but spread across oceans.",
 "First person to climb all 14 of the 8,000ers (1986)?": "Reinhold Messner finished the set in 1986, all without supplemental oxygen.",
 "Why did New Kingdom pharaohs switch from pyramids to hidden rock tombs?": "Pyramids were giant 'treasure here' signs and nearly all were robbed. Hidden tombs in a guarded valley were meant to be safer.",
 "Why is Tutankhamun so famous despite being a minor king?": "His small tomb was buried under debris from a later tomb, so robbers missed it. It was found almost intact in 1922.",
 "What was Enigma's key weakness that codebreakers exploited?": "Because a letter could never encrypt to itself, a guessed word ('crib') could be slid along the message to rule out positions.",
 "Which country's codebreakers cracked early Enigma first and shared it with Britain?": "Marian Rejewski and his Polish colleagues broke Enigma in 1932 and handed their work to Britain and France in July 1939.",
 "Historians estimate codebreaking shortened the war by about…?": "Many historians estimate Ultra intelligence shortened the war in Europe by around two years, saving millions of lives.",
 "Can you see the Great Wall from space with the naked eye?": "It's long but only a few metres wide and the same colour as the land around it. Astronauts confirm you can't pick it out.",
 "Who were the Terracotta Warriors made to guard?": "Qin Shi Huang, who unified China in 221 BC, was buried with an army of over 8,000 clay soldiers, each with a unique face.",
 "Did the Aztecs build Teotihuacan?": "Teotihuacan peaked around AD 450 and was abandoned centuries before the Aztecs arrived. They named it 'place where gods were born'.",
 "What happens at El Castillo at the equinoxes?": "Late-afternoon sun throws triangles of shadow down the steps that join the carved serpent head at the bottom.",
 "What killed Emperor Huayna Cápac, triggering the succession war?": "Smallpox raced ahead of the Spanish through trade routes around 1528, killing the emperor and his heir and sparking civil war.",
 "Besides steel and horses, what most helped the Spanish beat the Incas?": "Epidemics had killed huge numbers and a civil war between Atahualpa and Huáscar had split the empire. Pizarro arrived at the perfect moment.",
 "The real reason the Wall was built?": "Around 3.5 million East Germans had fled west by 1961. The GDR called it an anti-fascist rampart, but it faced inward.",
 "What brought the USA into WWII?": "Japan attacked Pearl Harbor on 7 December 1941. Four days later Germany declared war on the US.",
 "The brutal battle in Russia widely seen as the turning point of the war in Europe?": "From 1942 to early 1943 the Soviets encircled and destroyed the German 6th Army at Stalingrad. Germany never recovered the initiative.",
 "Laos's grim world record from the Vietnam War era?": "The US dropped over 2 million tonnes of bombs on Laos from 1964 to 1973, about one planeload every eight minutes for nine years.",
 "Why do vehicles drive on the left on Death Road?": "Downhill drivers sit on the left in Bolivian cars, so driving on the left puts them by the cliff edge where they can watch their outer wheel.",
 "What does an LLM like Claude or ChatGPT fundamentally do?": "It's trained to predict the next token, a word or word-piece. Doing that well across huge amounts of text produces surprisingly general abilities.",
 "What's an AI 'hallucination'?": "A fluent, confident answer that's simply wrong. The model predicts plausible text, which isn't the same as checking facts.",
 "Moore's law says the number of transistors on a chip doubles about every…?": "Gordon Moore's 1965 prediction, revised in 1975 to roughly every two years, held for about half a century.",
 "The 'runner's high' is now strongly linked to…?": "Endocannabinoids, the body's own cannabis-like molecules, rise with sustained exercise and reduce anxiety and pain.",
 "The 80-plus-year Harvard study found the strongest predictor of a happy, healthy life was…?": "The Harvard Study of Adult Development found the quality of close relationships predicted health and happiness better than wealth or fame.",
 "What does the evidence say about who built the Giza pyramids?": "Workers' villages, bakeries and tombs near the pyramids show paid, well-fed Egyptian crews, not slaves.",
 "Was Napoleon unusually short?": "About 1.69 m, average for a Frenchman then. The myth came from confusing French and English inches and from British cartoons.",
 "Did most gladiator fights end in death?": "Gladiators were expensive to train, so many bouts ended with the loser spared. Estimates suggest maybe one in five fights was fatal.",
 "The idea that 'thumbs down' meant death is…?": "Romans did use a thumb gesture ('pollice verso'), but which way meant death is unknown. The thumbs-down idea comes from a 19th-century painting.",
}
